### ISSUE TITLE
Viewer: "image attachment not found"

### ISSUE THREAD

**Issue by ShadowRain-** [chylex/Discord-History-Tracker#103]
I ran into something weird today, when viewing a log, it replaces all uploaded images with "image attachment not found" links, and yet when I click on the link, it displays the image just fine. I couldn't figure out what was preventing it from embedding them like it used to.

Thank you for all your work on this, it's a great tool!

**Comment by chylex** [comment]
Did you download the viewer file?

**Comment by ShadowRain-** [comment]
Yep, I downloaded it. Also it does it in both Firefox and Chrome.

**Comment by chylex** [comment]
Can't repro on my end, check if the Network tab in Firefox/Chrome dev tools is complaining.

**Comment by ShadowRain-** [comment]
Ok, my bad. Firefox didn't show anything under the network tab but Chrome did, and it just said the stuff was blocked (reason: "other"). I tried turning off privacy extensions and it looks like that fixed it. They'd never caused an issue for your stuff before so I didn't even think of it--sorry to bother you, and thanks for the point in the right direction!
