### ISSUE TITLE
More Settings: Specific Message Range only

### ISSUE THREAD

**Issue by Waryth** [chylex/Discord-History-Tracker#105]
Upon tracking all messages, we should be able to search certain message keywords to which part I only want to save. This should save up time saving large chunks of message history in a server or in a DM. I tried editing the text file but its all one liner for it to specify which messages I only wanna crop.

**Comment by chylex** [comment]
You can filter message contents using the viewer's filter feature, and save messages that match the filter into a new file.

**Comment by Waryth** [comment]
> You can filter message contents using the viewer's filter feature, and save messages that match the filter into a new file.

I'm using the **Option 2: Browser Console** as written [here](https://dht.chylex.com/) so I'm not sure if we're in the same page. I also use **Viewer** and it redirects me to https://dht.chylex.com/build/viewer.html even though it says..

"Download the **Viewer**, open it in your browser, and load the archive."

There's nothing for me to download for the Viewer?



> and save messages that match the filter into a new file.
I don't see that feature as mentioned above so I'm really confused.

**Comment by chylex** [comment]
It will appear once you set a filter. Download the viewer using your browser, saving a page is a feature of every browser.

**Comment by chylex** [comment]
The solution I mentioned earlier should work, I also outlined an idea for a more robust solution that would be much more powerful in #141.
