### ISSUE TITLE
More Settings: Filter Unwanted Message

### ISSUE THREAD

**Issue by Waryth** [chylex/Discord-History-Tracker#106]
Allow us to get rid of certain messages we don't want to be included for censoring purposes. I tried editing the text file but its all one liner for it to cut out unwanted messages.

**Comment by chylex** [comment]
The new desktop app version of DHT creates a database file, which can be edited using any database software that supports SQLite. If you're unfamiliar with database software and SQL, feel free to ask for guidance with a more detailed description of what you want to do.
