### ISSUE TITLE
Save media?

### ISSUE THREAD

**Issue by DarkShadowxx** [chylex/Discord-History-Tracker#109]
Is it possible to save all images/videos/files and replace the discordapp.com link by the local one?

**Comment by chylex** [comment]
You could grab all URLs from the archive file, which is just JSON, download them, and replace the links. Shouldn't be too difficult to write a script to automate it, but there's no officially supported solution.

**Comment by DarkShadowxx** [comment]
If it is not too hard anyway, I think this would be a cool feature to have?
A simple checkbox in the settings "download media files" or so.

**Comment by chylex** [comment]
Definitely not in the tracker itself, due to browser limitations regarding both downloads and bookmarklet sizes it'd be infeasible. I was more thinking a Python script as a utility separate from DHT.

**Comment by chylex** [comment]
I had some time so I wrote a Python 3 script to download attachments and image embeds, and patch the archive file. Run `python DownloadsEmbedsAttachments.py` to see usage, but basically `python DownloadsEmbedsAttachments.py archive.txt` will download everything from `archive.txt` in the same folder. Let me know if you run into any issues.

https://github.com/chylex/Discord-History-Tracker/blob/master/tools/DownloadEmbedsAttachments.py

**Comment by chylex** [comment]
I had some time so I wrote a Python 3 script to download attachments and image embeds, and patch the archive file.

Run `python DownloadsEmbedsAttachments.py` to see usage, but basically `python DownloadsEmbedsAttachments.py archive.txt` will download everything from `archive.txt` that's in the same folder as the script, put it into a new folder, and update the archive with local links. Note that you need to place the viewer in the same folder as the new archive for local links to work. Let me know if you run into any issues.

https://github.com/chylex/Discord-History-Tracker/blob/master/tools/DownloadEmbedsAttachments.py

**Comment by DarkShadowxx** [comment]
Thank you very much!
