### ISSUE TITLE
Replay history in current conversation

### ISSUE THREAD

**Issue by mnemex** [chylex/Discord-History-Tracker#113]
So one of the obvious use cases of a history file is to use it to move messages (albeit adding extra attribution) from one thread to another, or even from a conversation to a channel or vice versa.

The problem is, of course, that discord hard message limits means you can't just copy a displayed thread and paste it into a window.

So why not allow a "replay" functionality that lets the user select a file and replays the messages one at a time into the current window?

**Comment by chylex** [comment]
The archive is a standard JSON file, if you have a specific use-case that the viewer doesn't support, you can modify the viewer or write a script to manipulate the JSON file.

**Comment by chylex** [comment]
Closing since this feature is out of scope of the project.
