### ISSUE TITLE
"Cannot see any messages" error

### ISSUE THREAD

**Issue by firefang9212** [chylex/Discord-History-Tracker#114]
Something appears to have broken the tracker. Was trying to use it today but clicking "Start Tracking" always brings up the "Cannot see any messages" error. Was working fine yesterday but isn't today.

**Comment by chylex** [comment]
Unfortunate timing, I'm at the moment stuck with a shitty laptop that barely runs a browser, so I'm not yet sure how well Discord with all my dev tools is gonna run. I'll look into it in a bit and if it's a super simple fix I'll try to push it out, if not then it may have to wait a few days.

**Comment by AnastasiaDunbar** [comment]
Discord's layout has been rewritten.
Channels are within `<div class="scroller-… …" id="channels" …>`, each being `<div class="containerDefault-…>` with names in `<div class="name-… …" …>`.
Messages are wrapped inside `<div class="scrollerInner-…" …>` of `<div class="messagesWrapper-…">`, chat messages are `<div id="chat-messages-…" class="message-…" …>` with their contents in `<div class="markup-… messageContent-…">`.

**Comment by chylex** [comment]
So, Discord/Electron dev tools are nearly unusable. I found where the new message elements are (referenced commit), but autoscroll is not working atm.

**Comment by theyoosh** [comment]
Hi, it's still not working for me.

**Comment by chylex** [comment]
I won't release an update if half the tracker isn't fixed yet...

**Comment by srdecny** [comment]
I somehow managed to "fix" the autoscrolling -- see this commit: https://github.com/srdecny/Discord-History-Tracker/commit/ecd3328921377031c4a83ca666c6dde3747110ae. However, the speed of message archiving is ridiculously fast right now (>100 messages/second), so it would be wise to manually throttle the speed of archiving. I've tried to implement it, but I ran out of the time I'm willing to spend on this.

**Comment by chylex** [comment]
I'm actually surprised (if) that works - the point of

```js
      if (view.scrollTop > 0){
        view.scrollTop = 0;
      }
```

was that repeated unchecked scrolling used to freak out Discord where it would not load any messages at all until autoscrolling stopped.

I also remember introducing a delay because constant scrolling would never delete messages far into the future, so the browser would end up rendering every single message you loaded while autoscrolling at once, obviously not good. I don't know if that delay is still there or needed at all, but I'm wary of quick fixes without thorough testing because I saw Discord doing a lot of weird stuff over the years.

**Comment by srdecny** [comment]
Yeah, it's entirely possible it's not a fix at all, that's why I haven't made a PR.

**Comment by chylex** [comment]
Able to work on it properly now, hopefully won't take long.

**Comment by chylex** [comment]
As mentioned in the release notes, autoscrolling may randomly stall for a bit. Right now there's a timer that kicks in whenever that happens, I'm not sure about the reason for the stalls. Overall the autoscrolling seems faster than before though.
