### ISSUE TITLE
Information about the auto-scroll stalling

### ISSUE THREAD

**Issue by YYAshYY** [chylex/Discord-History-Tracker#117]
If the messages are not loading and this is the reason for the stall, it seems like nudging the scroll wheel on your mouse downward the tiniest bit causes it to immediately resume.

**Comment by chylex** [comment]
Moving the cursor also causes it to immediately pick up again, but I don't know if that's an issue in Discord or the browser, and whether it's possible to programatically trigger something that resumes it.

**Comment by ashleeskye0225** [comment]
Considering I was using the desktop version of Discord (the downloadable one, not the browser one), I’d say it’s not the browser
