### ISSUE TITLE
DHT will not switch to the next channel

### ISSUE THREAD

**Issue by FunnyInternet** [chylex/Discord-History-Tracker#119]
Doesn't switch to the next channel when I have the setting checked, I tried both on discord app and browser. It does seem to scroll the channel list down, but won't switch to it.

**Comment by Shebeba** [comment]
I don't know if the developer just done with dht or what, but in case it's useful to anyone in the future switching to the next person/group in direct message list seems to still work it's just the channels in a server

**Comment by chylex** [comment]
Switching to next channel is the single most commonly broken feature by Discord updates. If someone would like to fix it for a few weeks before it breaks again, I'll accept a PR.

**Comment by chylex** [comment]
If you come up with a working JS solution, feel free to PR. I tried a few elements but none are responding to simulated Alt+Down key event.

**Comment by TheTechRobo** [comment]
? For me in the desktop app the current desktop app DHT + both desktop app and Firefox Discord work with the channel switching.

**Comment by chylex** [comment]
It seems Discord has made some changes to the channel elements, so I can get rid of the hacky channel icon detection. We'll see how long until it breaks again.
