### ISSUE TITLE
Image attachment not found,

### ISSUE THREAD

**Issue by YYAshYY** [chylex/Discord-History-Tracker#120]
![Cfadsfapture](https://user-images.githubusercontent.com/43758023/97627293-8c88d800-1a01-11eb-9b10-0a13f038d033.PNG)

This happened with a couple images sent in different messages, but at similar times. When I first viewed the file, they were fine, but now 1-2 months later, they're gone. All other images remain.

Edit: 
It's because the tracker saved the images as the Discord URL you get when you copy the link of the image. Someone deleted the image in Discord, therefore, the URL became invalid. Would there be a way for you to create a separate link for images so that this does not happen?

**Comment by chylex** [comment]
You can see https://github.com/chylex/Discord-History-Tracker/issues/109#issuecomment-698043575 for a script that downloads all media into a folder and updates the archive file, I haven't written official documentation for it yet so it's easy to miss that the tool exists.

**Comment by YYAshYY** [comment]
Thanks!

**Comment by YYAshYY** [comment]
My bad, I don't really know how to run the script... where do I put it?

**Comment by chylex** [comment]
You need to download Python 3 and run it from the console/terminal, the command is in the linked comment.

**Comment by MavisCelus19201** [comment]
> You need to download Python 3 and run it from the console/terminal, the command is in the linked comment.

Does the script still work? All I get when I run it is this error

"Traceback (most recent call last):
  File "/home/chao/Software/DiscHist/DownloadsEmbedsAttachments.py", line 44, in <module>
    archive = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 27: invalid start byte"

I have the media files downloaded via DiscordChatExporter so if there's an alternative where I can use that then I'm up for that too.
