### ISSUE TITLE
Replies not included in archive

### ISSUE THREAD

**Issue by firefang9212** [chylex/Discord-History-Tracker#122]
Discord introduced a reply feature this week and naturally that has caused an issue with the tracker. The tracker is archiving regular messages as normal, but replies are completely skipped over.

**Comment by chylex** [comment]
I don't see replies in the app.

**Comment by firefang9212** [comment]
It hasn't been fully introduced to everyone yet but rather is being steadily made available to various servers. Only a few of the servers I'm in have it so far. https://twitter.com/discord/status/1328412825811906560

**Comment by chylex** [comment]
Will be fixed in next update.
