### ISSUE TITLE
The selected channel is not visible in the channel list

### ISSUE THREAD

**Issue by zzerexx** [chylex/Discord-History-Tracker#123]
DHT refuses to do anything now.
Everytime you click Start Tracking on any channel, an error message will popup saying
"The selected channel is not visible in the channel list."
Show up even though the channel is visible.

**Comment by ENunn** [comment]
Having the same issue

**Comment by chylex** [comment]
I figured out how to fix channel/message recognition, but Discord changed in a way where scrolling is now extremely fast and I can't tell if it's possible for it to go so fast that some messages get lost. I'd appreciate if as many people as possible tried [the patched version](https://gist.githubusercontent.com/chylex/050739839c581783deb2d16e337b681b/raw/e0008529a7ada38a18b236447372bd203422f0e1/DHT.js) (you can copy/paste all text into the browser/discord app console), and checked if all messages are recorded into the archive when DHT runs on their computer.

**Comment by IllegalFunctionCall** [comment]
After pasting the code into the ViolentMonkey console, the DHT button disappeared on discord?

**Comment by chylex** [comment]
This is not the userscript version, it's not going to work in violentmonkey.

**Comment by firefang9212** [comment]
Just gave it a test, the regular 0.27 version appears to be finding the channel normally again, it's fully working outside of still skipping replies. (I gave it a test before disabling it and trying the patched). The patched version on the other hand brings up the channel not visible error.

**Comment by chylex** [comment]
Looks like Discord reverted the update, not sure what they're doing.

**Comment by chylex** [comment]
I'm releasing an update that fixes reply saving and should support both current and reverted version of Discord, in case they decide to redo whatever broke it initially.

There is one issue with autoscroll I'd recommend watching out for, I think the scrolling is so fast that when you pause tracking, it lags and continues scrolling for another few seconds (but doesn't save any messages *after* tracking is paused).

**Comment by firefang9212** [comment]
That lag after pausing has been a thing since the August update btw.

**Comment by chylex** [comment]
I haven't used DHT in years and nobody reported the issue ¯\\\_(ツ)\_/¯

**Comment by firefang9212** [comment]
This error has just returned for me.

**Comment by chylex** [comment]
https://github.com/chylex/Discord-History-Tracker/issues/127

**Comment by ENunn** [comment]
Issue is still happening as of 12/29. Although I did find a weird temporary workaround. Start scanning a DM first, then pause and reset. Then scan a server. It's super weird and auto switching channels doesn't work (at least for me), but it looks like this server's being backed up.

**Comment by chylex** [comment]
I haven't seen this issue in a while, please reopen with more details if you're still experiencing it.
