### ISSUE TITLE
Recording parent message reference in reply data

### ISSUE THREAD

**Issue by maitre-piccolo** [chylex/Discord-History-Tracker#125]
Hello,

Recently Discord added a reply function. DHT currently saves the replies messages, but without a reference to which parent message each reply was a reply to.

It would be cool if DHT saved the parent message ID in the reply data.

Thanks.

**Comment by chylex** [comment]
It'd definitely be useful. I'd be happy to accept a PR that adds the parent message reference and updates the viewer to show the parent message (maybe in small text above the reply).

**Comment by chylex** [comment]
Released update with PR #133, thanks @Chupalika
