### ISSUE TITLE
tracker says The selected channel is not visible in the channel list

### ISSUE THREAD

**Issue by The-Stellaris-Effect** [chylex/Discord-History-Tracker#127]
discord seems to have updated which broke the tracker

**Comment by Gnomey123** [comment]
yeah, I'm getting it too

**Comment by guerra321** [comment]
I saw this issue too. This has something to do with the exact channel element not having the react metadata. My solution is to go from the top channel tree and iterate until you find the channel with channel.selected == true. I can put in a pull request after I implement it.

**Comment by guerra321** [comment]
Pull request submitted. Feel free to integrate it and paste it into your userscripts if you need it right now while we are waiting for chylex.

**Comment by chylex** [comment]
Updated.
