### ISSUE TITLE
works for DMs. not for servers at all still

### ISSUE THREAD

**Issue by The-Stellaris-Effect** [chylex/Discord-History-Tracker#129]
seems like the latest fix helped get DM's to work however servers still don't work. returning an error (The selected channel is not visible in the channel list.)

**Comment by chylex** [comment]
The latest fix changed literally nothing for DMs. I verified that it works for Discord Stable 73801 (c8242ba). If you have an older version then try older versions of DHT, if you have a newer version then I can't help because I don't have it.

**Comment by The-Stellaris-Effect** [comment]
ok

**Comment by The-Stellaris-Effect** [comment]
i just updated it. seems like i needed to restart my browser to get it working
