### ISSUE TITLE
Create filter by server in viewer

### ISSUE THREAD

**Issue by eduarcor** [chylex/Discord-History-Tracker#131]
Could you please create filter by server? If you have more than one server, is hard to see quick what channels belongs to any server... so filter by server could be really useful.
Should be great to create filter by privates messages in the same fashion.
Thank you.

**Comment by chylex** [comment]
The next update of the app will support filtering by channel. If you have a a lot of different channels, it might require a few too many clicks to select all the channels you want, but you'll be able to try it out and open a new issue if you'd like some improvements to the user interface.
