### ISSUE TITLE
Could not parse, see console for details

### ISSUE THREAD

**Issue by TailorBlaze** [chylex/Discord-History-Tracker#132]
Hi, I'm having an issue (saved in html) and whenever I'm trying to load the HTML file in either the online viewer or the offline viewer, no matter which channel I try to open or how many messages it has, it will not load and just says :
"Could not parse  -xyz-, see console for details"

(26) Unchecked runtime.lastError: The message port closed before a response was received.
viewer.html:8 SyntaxError: Unexpected token < in JSON at position 4
    at JSON.parse (<anonymous>)
    at i (viewer.html:8)
    at FileReader.n.onload (viewer.html:8)
i @ viewer.html:8

Any tips on how to solve this? Cheers.

**Comment by chylex** [comment]
Does it always happen or are there specific conditions, i.e. a certain amount of messages or channels?

**Comment by TailorBlaze** [comment]
No there wasn't a certain amount of messages that caused this, tried it with a brand new channel with 5 test messages and tried it with an old one with 25203 messages, it gave the same error.
Asked around and dug a bit around the interwebs, a friend said it might be because of a typo and suggested 
trying some lambda and () => {}  that wasn't it, and after running some commands, solving a few things like an issue with my 443 port in Apache, installing Opera, reinstalling Notepad++ etc.. and just going around updating a bunch of stuff related to this solved the issue and it works now as intended, thanks :)

**Comment by chylex** [comment]
Sounds like it was most likely an outdated browser, if it was solved by installing/updating Opera. In either case, closing the issue.
