### ISSUE TITLE
How to automate getting messages ever X minutes from a sepcific channel

### ISSUE THREAD

**Issue by ahmedlone127** [chylex/Discord-History-Tracker#136]
Your app was the exact thing I was looking for , I tested it and it worked fine , now i want to automate runnin so that after every  X mins it would get the messages and create a new csv , The code is long and looking at all of it will take a lot of time , if you have an easy solution please let me now

**Comment by chylex** [comment]
There is no easy solution, browser scripts are not a good tool for this kind of automation. You could probably make it work with a custom browser (Chromium) or browser automation tool (Selenium), but you'd need to build it basically from scratch.

**Comment by ahmedlone127** [comment]
Thank you , I will look into it
