### ISSUE TITLE
Becomes extremly slow in headless firefox version

### ISSUE THREAD

**Issue by ahmedlone127** [chylex/Discord-History-Tracker#138]
I am using selinum to automate your program but in headless mode it becomes extremly slow

**Comment by mahanstreamer** [comment]
Use https://github.com/Tyrrrz/DiscordChatExporter

**Comment by chylex** [comment]
I cannot guarantee any sort of performance or lack of issues when using either Discord or DHT in headless browsers.

You're free to investigate performance issues with a profiler, and if you can show that DHT is the reason for bad performance I will take a look at the profiler data, but when it comes to use cases DHT doesn't officially support you're basically on your own.
