### ISSUE TITLE
Viewer.html is missing from web download

### ISSUE THREAD

**Issue by AirplanegoBrr** [chylex/Discord-History-Tracker#139]
The viewer.html is missing from the web download im not sure why. Here is the file that needs to be added 

[viewer.zip](https://github.com/chylex/Discord-History-Tracker/files/6388679/viewer.zip)

**Comment by chylex** [comment]
I don't understand what you're saying, you can download the viewer through the official website.

**Comment by AirplanegoBrr** [comment]
https://github.com/chylex/Discord-History-Tracker/tree/master/web/build there is no viewer.html

**Comment by chylex** [comment]
There shouldn't be one, the folder is part of the automated build process.
