### ISSUE TITLE
Incremental saving would be nice.

### ISSUE THREAD

**Issue by stkAnon** [chylex/Discord-History-Tracker#14]
I love this thing, but I've had to restart my archive 2 or 3 times on Chrome now just because I left it overnight on a big server and it keeps crashing.

Would it be possible to store the data in a cookie or something even before it's been downloaded?

**Comment by chylex** [comment]
The DHT website specifically states that this is not intended to be used on large servers. Neither cookies nor browser storage provide enough space to store more than maybe half an hour worth of continuous tracking (and the tab may be running out of memory if it's crashing overnight), so downloading the file manually is the only option.

Other than that, DHT already has incremental saving in that you can load a saved archive before tracking and it will stop when it reaches the last saved message, but it's not intended to support millions of messages.
