### ISSUE TITLE
Discussion about new message tracking tool & archive format based on a database

### ISSUE THREAD

**Issue by chylex** [chylex/Discord-History-Tracker#141]
I would like to introduce my plans for a new tool, which is based on DHT but hopefully fixes major issues that come with entirely in-browser tracking, and the current JSON archive file format:

- The entire archive must be loaded in the browser's memory at once, which makes DHT difficult to use for millions of messages
- The process of combining and generating archive file can also take a long time with large archives
- If the browser or computer crashes, you lose the entire progress
- It is impossible to automate DHT and have it update the archive on its own
- Due to the need to keep the archive file as small as possible, the JSON format is fairly unintelligible and has caused unfortunate bugs in the past
- JSON is not as friendly to data analysis and manipulation as for ex. an SQL database could be
- Additional functionality, such as the ability to download media and attachments, cannot be done in the browser during tracking

On the other hand, the bookmarklet and userscript are simple to use and don't require a lot of additional setup. For most people, the way DHT works right now is enough and I don't intend to change that - but I'm planning to create a separate tool, which would be much more robust and useful for the rest.

## How

The idea is that instead of storing all messages inside the browser, the tracker script would send them to a program you would run separately. The program would save all messages in an SQL database file, and also have a graphical user interface with settings and additional tools:

- A way to export the database into the JSON-based archive file, or generate a viewer with the archive embedded - including the possibility to filter exported messages
- The ability to download media & attachments I mentioned earlier
- More ideas...?

This would solve all aforementioned issues, and also make it easy to implement new features (such as password-protected archives).

Not sure when I'll have the time to work it all out, but I wanted to get the idea out there for feedback.

## Implementation

Implementation details are subject to change and open to discussion.

Right now I'm thinking that the program would be in C#, based on .NET Core + Avalonia for multiplatform Windows/Linux/Mac GUI. The program would start a fully local server the tracking script would send messages to, and store them in an SQLite database.

The tracking script - or even multiple ones that could run in multiple browser tabs - would communicate with the program via XHR (I verified Discord's CSP rules allow requests to localhost), with some form of authentication (like a randomly generated port + password combo) to ensure a malicious website cannot make valid requests.

**Comment by fluunke** [comment]
Thanks to WASM, it's quite simple to run SQLite databases directly in the browser. The databases are easy to load and export in a well known format, the current ease of use wouldn't be impacted, one could store media files as BLOBs, and I can imagine fair improvements in performance.

Thoughts on that approach?

**Comment by chylex** [comment]
> Thanks to WASM, it's quite simple to run SQLite databases directly in the browser. The databases are easy to load and export in a well known format, the current ease of use wouldn't be impacted, one could store media files as BLOBs, and I can imagine fair improvements in performance.
> 
> Thoughts on that approach?

That doesn't solve the much more important problem of where to store the data while DHT is running so that it doesn't increase memory requirements (especially when storing media blobs) and you don't lose everything if the browser closes, plus it introduces new problems of the script getting too large to work as a bookmarklet.

**Comment by chylex** [comment]
Playing with a prototype, the database tracks more information than the old format (for ex. enough to fully recreate embeds, although the updated viewer can only do a few kinds at the moment) and should be about 50 MB per 250 K messages (pessimistic estimate). Right now it generates a viewer file that's about the same size as the database in about 2 seconds.

![obrazek](https://user-images.githubusercontent.com/3685160/120944194-79767d00-c733-11eb-935a-70a0bdc895af.png)

Really happy with how it's going, and also thinking about the possibility of adding better support for very large databases where generating and loading the viewer file would not be feasible. Since the app acts as a local server, there could be a lightweight viewer that communicates with the app to load messages and downloaded attachments on the fly. There are many more possibilities now compared to the way DHT works now, that the app will most likely be the main focus for new DHT features in the future.

**Comment by chylex** [comment]
Released the first version and updated website - https://dht.chylex.com/

**Comment by TheTechRobo** [comment]
Works well, 'cept for a bit slow (which si to be expected, it's a lot more complicated). One comfort feature I'd like is exporting back to the old-fashioned format

**Comment by chylex** [comment]
> Works well, 'cept for a bit slow (which si to be expected, it's a lot more complicated). One comfort feature I'd like is exporting back to the old-fashioned format

Got a specific use case for it?

**Comment by TheTechRobo** [comment]
I don't know, it's just a lot easier to read if for some reason you don't have the viewing tool.

**Comment by chylex** [comment]
> I don't know, it's just a lot easier to read if for some reason you don't have the viewing tool.

That's why the option to save the viewer exists in the app.

**Comment by TheTechRobo** [comment]
I gues, yeah. Scratch my suggestion

**Comment by chylex** [comment]
I enabled Discussions, it's probably a better way of dealing with feedback than a single issue - https://github.com/chylex/Discord-History-Tracker/discussions

**Comment by mahanstreamer** [comment]
This was just brought to my attention.

One thing i would like to see is the ability to update and listen to messages as they come in as well . This, and many other potential issues, could be solved with something like Headless Chromium that way servers can be archived in the background. The idea is that once you open the desktop app, a headless chromium instance will open and get the list of servers. After that, you would click on the servers you ant to archive, what time length you want to archive, and a script in the headless Chrome will take care of the rest. I'd be willing to contribute to an effort like that, but im not sure if that's out of the scope of the desktop app you have.

Also how do you plan on dealing with the memory issue? Last time i used DHT the browser sometimes crashed when dealing with too many issues. Maybe you could delete old messages in memory as you scroll up, but i'm not sure how that would work in implementation.

**Comment by chylex** [comment]
> One thing i would like to see is the ability to update and listen to messages as they come in as well.

If you disable autoscroll, the app version of DHT is able to do that. The only difference is that you have to open the browser and start tracking manually, but you can open multiple tabs with different channels and track all of them at once.

> Also how do you plan on dealing with the memory issue?

When using the app, the tracking script doesn't keep any messages in memory, so if you still have memory issues then it's either Discord leaking memory or a bug in the browser (or unlikely but always a possibility it's a bug in the tracker script) and a memory profile might help identify where it's leaking.

**Comment by COLDsteem** [comment]
How do you open a previously saved database? DHT App offers "Open or Create Database", but once I click the button, SAVE dialog shows only, no matter what.

**Comment by chylex** [comment]
There's just one dialog. If you give it a database file that already exists, it just opens it.

**Comment by COLDsteem** [comment]
Oh... It says it already exists and if I want the replace it. Also, the dialog button is Save, and in Windows that usually means you'll overwrite the file. It's confusing because of that.

**Comment by chylex** [comment]
Yea, there just wasn't much point to making two separate dialogs because it works the same way and the Open dialog doesn't let you create a new one. If it's too confusing I might change it.

**Comment by FlashlightET** [comment]
so how do i scrape messages now? i have them all saved with the new tool, and now I can't read the file because it isn't json anymore, and the file is just garbage when loaded into notepad++
i had a python script specifically written to scrape from the json files is there any way to convert

**Comment by chylex** [comment]
> so how do i scrape messages now? i have them all saved with the new tool, and now I can't read the file because it isn't json anymore, and the file is just garbage when loaded into notepad++
> i had a python script specifically written to scrape from the json files is there any way to convert

Read the website, I'm not going to re-explain it because the website already explains how to view it and what the format is.

**Comment by Agent-Rogue** [comment]
i wonder if there's a way to add functionality to migrate from the old format to the new one. this would be particularly useful in cases where one already archived a large server in the old json format but for whatever reason no longer are in said server. ideally the implementation could allow the files to be combined into the existing archive.dht file

**Comment by Agent-Rogue** [comment]
i wonder if there's a way to add functionality to this to migrate all the old json files generated by previous versions to the new SQLite DB so it's all in one spot and in a better format for viewing.

**Comment by TheTechRobo** [comment]
has the image downloading feature been implemented yet?

**Comment by TheTechRobo** [comment]
keep us posted! love your work :D

**Comment by TheTechRobo** [comment]
Is a CLI planned? Would be nice for server use.

**Comment by chylex** [comment]
Need more details on your use case. The app already supports specifying the database file and port + token for communicating with the browser script, but you would still need to automate the browser part of the tracking.

**Comment by TheTechRobo** [comment]
It was for #157, so I just need to be able to have no gui whatsoever. Seems like those options would fix it. Thanks!

**Comment by chylex** [comment]
I think the overall discussion can be closed. Any further issues or ideas can be opened either as a new [Issue](https://github.com/chylex/Discord-History-Tracker/issues), a new [Discussion](https://github.com/chylex/Discord-History-Tracker/discussions), or continued in the already opened issues/discussions.
