### ISSUE TITLE
Suggestion : Save from this date & Time

### ISSUE THREAD

**Issue by Warziget** [chylex/Discord-History-Tracker#143]
Hello, 
Awesome work for this pluggin / application.

I would like to suggest you to add in settings, "Save from [DATE]" and "Save from [TIME]" in order to not have to save the entire conversation / channel but just the part we need in order to keep it. 

I'm currently using your Browser Script, it might have different feature between your app and you script pluggin, but if you can, it would be cool to have it on both of your project.

Thanks by advance, Cordialy, Warziget

**Comment by chylex** [comment]
The app already has options for removing/keeping messages between two dates, but currently does not support automatically stopping when reaching a specific date. I have opened a new issue for this, as part of a larger improvement for the app: #169
