### ISSUE TITLE
Multiple tupperbox proxies treated as a single one

### ISSUE THREAD

**Issue by MageofMagnolia** [chylex/Discord-History-Tracker#146]
When I tried saving messages in a channel with multiple tupperbox proxies, all of the messages were saved as if only one proxy had sent it. I believe it treats the most recent proxy as the sender. It's very confusing to see a single proxy when reading it back.

**Comment by chylex** [comment]
Duplicate of #64?

**Comment by MageofMagnolia** [comment]
It looks like it could be, my bad!
