### ISSUE TITLE
Support for Threads

### ISSUE THREAD

**Issue by kheptagon** [chylex/Discord-History-Tracker#147]
Discord just added the Threads feature, and DHT can't yet record the contents of threads.

**Comment by chylex** [comment]
So, threads appear to be somewhat complicated. I was unable to find a 100% reliable way to detect threads, so there are some caveats:
- newly created threads cannot be tracked until you switch to a different server and back, or restart Discord
- the order of threads isn't saved
- the first message in a thread is actually a reply to the message that initiated the thread, so you will only see its contents if the initiating message itself was saved

**Comment by kheptagon** [comment]
Those sound pretty manageable.

**Comment by chylex** [comment]
It looks like Discord changed something, the internal data DHT uses to track messages and channels isn't getting updated anymore until you switch servers/channels, so I will have to change quite a bit more.

**Comment by kheptagon** [comment]
I was already having to manually switch channels, so that isn't an issue for me.

**Comment by chylex** [comment]
Turns out the new tracking method no longer sees the first message in a thread as a special reply but as the message itself, except it's linked to the original channel instead of the thread channel. I guess that's a fair trade-off for reliable message tracking, I'm not going to look further into it for now.

**Comment by chylex** [comment]
Released update for the app. I will look into updating the browser-only version later.

**Comment by chylex** [comment]
I think the recent-ish fixes to the browser-only version made tracking threads work, but it's not at the same level as thread support in the app version. Regardless, I don't have the time or will to support new Discord features in the browser-only version, so threads in the browser-only version are what they are.
