### ISSUE TITLE
Unresolved mentions, crash the viewer in the Desktop-App

### ISSUE THREAD

**Issue by Freigeist** [chylex/Discord-History-Tracker#148]
I recently archived some channels of a server and noticed, that if a user that didn't write a single message in the capture gets mentioned, or a room, that wasn't part of capture, is being mentioned, the viewer crashes, because they aren't in the channel/user table of the database.

The functions `getChannelName(channel)` and `getUserTag(user)`  are the ones throwing errors. If you add the channels and users manually to the SQLite database, the viewer works fine. So users/channels need to get resolved and stored at capture time or the functions in the viewer need to return something like "@unknown-user"/"#unknown-room", I'd prefer the first option though.

**Comment by chylex** [comment]
I'm not aware of any way to reliably get user/channel data outside of the message list. There used to be a fallback so that the viewer doesn't crash if a user/channel is unavailable, but I think I broke it some time ago.
