### ISSUE TITLE
Delete conversation, channel or even server

### ISSUE THREAD

**Issue by eduarcor** [chylex/Discord-History-Tracker#150]
Having from data backed up from discord, we could have conversations, channels or servers that are not meaningful anymore, it should be great to have a way to delete them.

**Comment by chylex** [comment]
The next update will have some new filters in the Viewer tab, with an option to apply those filters to the database (either keep only messages matching the filters, or remove messages matching the filters). If that isn't enough, the database can always be edited manually using any database software that supports SQLite.
