### ISSUE TITLE
Local Image Support?

### ISSUE THREAD

**Issue by MavisCelus19201** [chylex/Discord-History-Tracker#151]
Any chances of this being added in some way? I know of the script but using that only brings up this error here.

"Traceback (most recent call last):
  File "/home/chao/Software/DiscHist/DownloadEmbedsAttachments.py", line 44, in <module>
    archive = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 27: invalid continuation byte
"

One idea is being able to patch it like the script but putting in images afterward somehow, I have images downloaded by DiscordChatExporter so being able to slot those in somehow would be nice, assuming it's feasible, if not then there might be another way. Being able to store images locally would help a ton as far as backing up locally goes.

**Comment by chylex** [comment]
Downloading attachments and embeds is work-in-progress for the app version of DHT. I don't know why the script isn't working, I'll investigate later.

**Comment by mwaitzman** [comment]
does it work in another version of DHT?

**Comment by MavisCelus19201** [comment]
> does it work in another version of DHT?

Didn't make a different when I tried other versions of DHT.

**Comment by TheTechRobo** [comment]
did you use the desktop app to make the archive?

**Comment by MavisCelus19201** [comment]
> did you use the desktop app to make the archive?

I did.

**Comment by chylex** [comment]
The script was made before the app, it doesn't work with its archives.

**Comment by mwaitzman** [comment]
> 
> 
> The script was made before the app, it doesn't work with its archives.

would you be willing to make a new script that _does_ work with the app's archives? It would be much appreciated. Failing that, could you direct me to the relevant resources in order to make it myself?

**Comment by chylex** [comment]
There is a work-in-progress branch to build this functionality directly into the app.

**Comment by mwaitzman** [comment]
ooh okay I didn't know that. Thanks

**Comment by TheTechRobo** [comment]
@mwaitzman The database structure is quite simple. While chylex is sitll working on the functionality, you can look at my script to extract all (not  just attachments) URLs, but it should be fairly straightforward to just get attachments (remove the part of the script for message data).

Alternatively you can just look at the comments, they show the database structure.

**Comment by mwaitzman** [comment]
> @mwaitzman The database structure is quite simple. While chylex is sitll working on the functionality, you can look at my script to extract all (not just attachments) URLs, but it should be fairly straightforward to just get attachments (remove the part of the script for message data).
> 
> Alternatively you can just look at the comments, they show the database structure.
> 
> [TheTechRobo/discordhistorytracker-urls-extractor](https://github.com/TheTechRobo/discordhistorytracker-urls-extractor)

oh okay, thank you!

**Comment by vielavlrs** [comment]
As a non-developer and wants to use this functionality, how can I run this script? Especially @TheTechRobo script. Thanks for the help!

**Comment by TheTechRobo** [comment]
@vielavlrs For my script:

Make sure you've got Rust and Cargo installed. You can install it at https://rustup.rs

Clone the repository I linked. Go into the folder, and `cargo run /path/to/archive.dht`. Any URL in `ignores.url` will be skipped, and URLs that are extracted are automatically put there. **urls.url will be overwritten with the URLs extracted.**

If you need help contact me:

- TheTechRobo#7420 on Discord
- TheTechRobo on hackint IRC

**Comment by TheTechRobo** [comment]
@vielavlrs What do you mean by connecting the two?

**Comment by vielavlrs** [comment]
@TheTechRobo I have used only python and it generated urls.url and ignores.url files. But I dont know what to do with it. I installed Rust and Cargo then ran the cargo run archive.dht (I put the dht file in the cloned repo) however I encountered this error 
![image](https://user-images.githubusercontent.com/93360948/166303593-f96bca1c-1e4a-4db4-8f21-151dd899b999.png)

**Comment by vielavlrs** [comment]
@TheTechRobo there have been a lot of errors for my rust installation. However, I was able to run the python and was able to generate the urls.url and ignores.url but I dont know what to do of them to view the images locally using the DHT viewer

**Comment by vielavlrs** [comment]
I completely misunderstood what the script does. I have found a solution to my problem. Thanks!

**Comment by TheTechRobo** [comment]
@vielavlrs Sorry I didn't answer. Glad you fixed it.

**Comment by chylex** [comment]
I have created a beta release with a discussion thread for feedback: https://github.com/chylex/Discord-History-Tracker/discussions/183

**Comment by chylex** [comment]
Closing as resolved in favor of the discussion, if there are no issues or ideas in a few days, I'll release the beta as a full update.
