### ISSUE TITLE
suggestion: merging old json format files into the new SQLite database format

### ISSUE THREAD

**Issue by Agent-Rogue** [chylex/Discord-History-Tracker#154]
been trying out the new desktop version which seems to work pretty well however for previous files which were created with the old json format, which don't necessarily display correctly or allow me to export it as an HTML document (currently my way of dealing with images), a way to merge them into the new sqlite database in the desktop application would be very useful

**Comment by chylex** [comment]
I have created a beta release with a discussion thread for feedback: https://github.com/chylex/Discord-History-Tracker/discussions/185

**Comment by chylex** [comment]
Closing as resolved in favor of the discussion, if there are no issues or ideas in a few days, I'll release the beta as a full update.
