### ISSUE TITLE
Doesn't always track messages. Scrolls too quickly/zealously?

### ISSUE THREAD

**Issue by will-ca** [chylex/Discord-History-Tracker#155]
Seems to scroll too quickly, moving past recent messages before they're loaded/saved when first switching to a channel.

Jumping back to the present gives messages a second chance to be saved, but not reliably.

Sometimes leaves empty sections in the middle that won't be saved, until a second pass.

Also autoscrolls long past point where no further messages are being saved— So it will keep jumping upwards, while the saved message count stays constant. (I suppose this might hint at overzealous scrolling jumping away before any messages can be loaded and compared to what's already been saved.)

On Chrome. Basing all this on the "`X` messages from `N` channels display", and whether it ticks up or not. Not sure how to give any more detailed description or reproduction steps.

Using a file with tens of thousands of pre-existing messages.

**Comment by will-ca** [comment]
Hm. Also seems to autoscroll regardless of whether "Autoscroll" is turned on.

**Comment by chylex** [comment]
See https://github.com/chylex/Discord-History-Tracker/issues/156#issuecomment-980796791.
