### ISSUE TITLE
Messages go in wrong channels.

### ISSUE THREAD

**Issue by will-ca** [chylex/Discord-History-Tracker#156]
Adding to an existing log, and according to the viewer, I've been having messages show up in the wrong channel.

It seems they show up in the channel after the one they're supposed to be in.

I've been opening all channels once before starting the tracking, to pre-load them because of #155, and then using the `ALT`+`DOWN` hotkey to switch to them in sequence during tracking, if that affects anything.

**Comment by chylex** [comment]
I cannot reproduce either #155 or this issue w/ the Discord app, which is based on the same core as Chrome. One of the issues you mention is that the Autoscroll checkbox isn't working, which makes me think something is weird with your browser. Have you tried tracking in a different browser or the Discord app?

**Comment by chylex** [comment]
Unable to reproduce the issue. If you're still experiencing it, please create a Discord server with some channels and messages for testing, record a video of the whole process that shows the bug happening, and post:
- (1) the exact DHT version you're using
- (2) the recorded video
- (3) the archive file created in the video
- (4) a link to the test server

You can email me everything at `contact@chylex.com` to avoid publicly exposing your Discord username/discriminator.

**Comment by will-ca** [comment]
I always meant to get a sharable reproducer or redacted recording done for this. Suspected it might require lots of server message history and a big existing log, for race condition-ey stuff.

Anyway, for the record: On the server where this was happening, I am no longer able to reproduce any part of either this issue or the linked one.
