### ISSUE TITLE
Channel switcher skips thread channel

### ISSUE THREAD

**Issue by TheTechRobo** [chylex/Discord-History-Tracker#159]
With this:

![image](https://user-images.githubusercontent.com/52163910/145031940-85a8eba1-22c1-44ac-95d4-ae8339455dd5.png)

After #gengral was finished, it went on to #shiteposting; it skipped #meems.

I think that's because it has the thread icon, and the channel switcher uses that to switch?

**Comment by chylex** [comment]
The switcher knows about thread icons, if it fails it's possible Discord changed the icon at some point.
