### ISSUE TITLE
Issue with use of Tupperbox?

### ISSUE THREAD

**Issue by LJB94x** [chylex/Discord-History-Tracker#160]
A thread I was trying to save consisted of a lot of messages sent via Tupperbox proxies. The messages all saved, however when loading into the viewer it showed them as all having been sent by the same Tupper proxy, rather than differentiating. 
I've used DHT to back up threads where Tupperbox was utilised in the same manner before and not had an issue

**Comment by chylex** [comment]
Saving usernames per-message instead of per-user is not and has never been supported. There is already an issue open about this, so I'm closing this in favor of #64.
