### ISSUE TITLE
v.31 no longer tracks direct messages

### ISSUE THREAD

**Issue by ssokolow** [chylex/Discord-History-Tracker#161]
With the v.31 DHT bookmarklet or DOM Inspector snippet, fresh from <https://dht.chylex.com/>, in a freshly reloaded Discord tab in Firefox, I get a "The selected channel is not visible in the channel list" dialog when I click "Start Tracking" on a direct messages "channel".

**Comment by ssokolow** [comment]
That doesn't appear to fix the problem for me.

I did the following and I'm still getting the same error:

1. Clone the repo (at edc23d616dcc0d067fe83de018cf5a713150c2e9)
2. Run `python3 build.py` and receive a `Done` with no error messages
3. Reload my Discord tab to be sure I'm on the newest version
4. Copy the contents of `bld/track.js` into the DOM Inspector's console tab
5. Upload & Combine to load my existing log
6. Click Start Tracking

**Comment by chylex** [comment]
The browser script isn't updated yet. I noticed some weird autoscroll behavior so I'm setting up a test to make sure it's not skipping messages.

**Comment by chylex** [comment]
There is a skipping issue, doesn't happen every time but I've been able to reproduce it several times by clicking away from the browser while it's tracking.

**Comment by chylex** [comment]
Update released.

**Comment by ssokolow** [comment]
Thanks. :)
