### ISSUE TITLE
Real-time tracking

### ISSUE THREAD

**Issue by xnvmx** [chylex/Discord-History-Tracker#163]
Is it possible to add real-time tracking messages continuously? I am often on servers that clean the chat several times a day and I would like to see these messages and save when I'm not on the discord...

**Comment by chylex** [comment]
The app will track continuously if you turn off autoscroll.

**Comment by xnvmx** [comment]
Ohh yes. I just found this option and wanted to close issue thread, but you answered faster :)
I've been looking for something like this for months, perfect app <3

**Comment by xnvmx** [comment]
I do not know why, but Ctrl + Shift + I has not been working on my Discord application in Windows for some time. Do I have to do this through the browser?

**Comment by chylex** [comment]
They recently released an undocumented change that disables Ctrl+Shift+I in the app. You can re-enable it manually: https://www.reddit.com/r/discordapp/comments/sc61n3/cant_inspect_element_anymore/hu4fw5x/
I will add an option to the app to do it automatically.

**Comment by xnvmx** [comment]
That's one more question. How to continuously track not only one channel but several servers with at least 5 channels each?

**Comment by chylex** [comment]
The only way is to either automate the channel switching yourself, or open Discord in multiple tabs in a browser and run the tracking script in all of them.

**Comment by xnvmx** [comment]
That's what I do right now. I'm working on many tabs in the browser, but I thought there was an easier way and less resource-consuming, because chrome with so many tabs takes a lot of RAM.
