### ISSUE TITLE
BUG: channel with no history (i.e. fully removed) stalls DHT until next channel selcted

### ISSUE THREAD

**Issue by Neo-Desktop** [chylex/Discord-History-Tracker#164]
As I've observed with my own servers - if I have a channel with no history (basically one that has all messages removed) the tracker javascript stalls until the user intervenes by clicking on the next channel with history.

This doesn't seem like intended behavior hence the BUG tag

Thank you for creating such a wonderful open source project~

**Comment by TheTechRobo** [comment]
Yeah, happens to me. I figured it's so uncommon that I was too lazy to  file a whole issue for it, and also they're usually at the start of crawls because usually it's things like announcements and welcome channels that are empty. Glad someone else stepped up :P
