### ISSUE TITLE
User IDs unmatched after uploading/combining multiple logs with different channels into a single file.

### ISSUE THREAD

**Issue by stkAnon** [chylex/Discord-History-Tracker#17]
One channel:
![screenshot from 2017-10-27 13-04-19](https://user-images.githubusercontent.com/8258259/32123818-8557f1d6-bb1a-11e7-99ed-58ffac7eb0ef.png)

After combining:
![screenshot from 2017-10-27 13-04-10](https://user-images.githubusercontent.com/8258259/32123828-8c9c3592-bb1a-11e7-9947-7c3dcf8edfec.png)

~~I'm not sure if this is an actual problem with the final file or just a viewer bug.~~ It doesn't seem to affect messages from the first dataset uploaded, but consistently shows up in the rest of the channels.

However, it doesn't affect every single message from every user in every channel. The last page or so in some (not all) of the channels still seem display properly, and sometimes only certain usernames are affected.

Example of a cut-off point where it affects one message but not the next one from the same user:
![untitled2](https://user-images.githubusercontent.com/8258259/32125906-f9e1c9b6-bb22-11e7-8ccf-5093080b7bb8.png)
![untitled](https://user-images.githubusercontent.com/8258259/32125913-fc4ab906-bb22-11e7-9994-9e50658d7a07.png)

In the above example, the change in displayed username also corresponds to a change in the `"u"` index saved for the messages in the `dht` file, so it's not just a display error from the viewer. The first, incorrectly identified message is labelled with `"u":0`, while the second, correctly labelled message is identified with `"u":19`. The original file identified the user with a value of `"u":0`; however, I believe this is coincidental as the issue affects more than one user at once, and another message I checked had its user changed from `"u":2` to `"u":5`, which rendered incorrectly.

I have not been able to identify whether the incorrectly tagged messages have `"u"` values that would be equivalent to the correct user in any of the other files that were combined into a single record.

**Comment by chylex** [comment]
I think I actually never thoroughly tested combining multiple logs... weird. I'll look into that soon.

**Comment by chylex** [comment]
Sorry it took so long, next update will have the fix. If you have the original separate archives, you will be able to combine them properly without re-logging all the messages.
