### ISSUE TITLE
[DHT] Error retrieving selected channel. TypeError: Cannot read property 'innerText' of null

### ISSUE THREAD

**Issue by skiddling** [chylex/Discord-History-Tracker#172]
hi, i met this error, the dht always show it's waiting, and when i try to start tracking, the console show this error, Error unknow channel,please help me, thank you so much
[DHT] Error retrieving selected channel. TypeError: Cannot read property 'innerText' of null
    at Function.getSelectedChannel (<anonymous>:16:3114)
    at onMessagesUpdated (<anonymous>:180:24)
    at <anonymous>:225:4
    at Object.setIsTracking (<anonymous>:95:1274)
    at HTMLButtonElement.<anonymous> (<anonymous>:53:399)
    at HTMLButtonElement.r (ac661b3e96533b7f8ccf.js:126)
(anonymous) @ ac661b3e96533b7f8ccf.js:130
getSelectedChannel @ VM491:16
onMessagesUpdated @ VM491:180
(anonymous) @ VM491:225
setIsTracking @ VM491:95
(anonymous) @ VM491:53
r @ ac661b3e96533b7f8ccf.js:126

**Comment by ThisIsRedditulous** [comment]
I'm also encountering this issue with the desktop application.
Here is my console output which looks very similar to the post above:

[DHT] Error retrieving selected channel. TypeError: Cannot read property 'innerText' of null
    at Function.getSelectedChannel (<anonymous>:16:3114)
    at onMessagesUpdated (<anonymous>:180:24)
    at <anonymous>:225:4
    at Object.setIsTracking (<anonymous>:95:1274)
    at HTMLButtonElement.<anonymous> (<anonymous>:53:399)
    at HTMLButtonElement.r (ac661b3e96533b7f8ccf.js:126)
(anonymous) @ ac661b3e96533b7f8ccf.js:130
getSelectedChannel @ VM498:16
onMessagesUpdated @ VM498:180
(anonymous) @ VM498:225
setIsTracking @ VM498:95
(anonymous) @ VM498:53
r @ ac661b3e96533b7f8ccf.js:126

**Comment by TheTechRobo** [comment]
Having the same problem.

**Comment by An-Unlucky-Duck** [comment]
I'm having the same problem as well. Came here to post about it.

**Comment by chylex** [comment]
Please add reactions instead of commenting, so that people who are waiting for a resolution don't get unnecessary notifications. I can look into the issue in a few hours.

**Comment by chylex** [comment]
Fix released in v35.1
