### ISSUE TITLE
Different Versions of DHT Not Working For DMs and/or Servers

### ISSUE THREAD

**Issue by princessbinas** [chylex/Discord-History-Tracker#174]
This issue is a bit of a combination of issues #108, #161, and #129 depending on which version of DHT is used and which method of accessing Discord is used. I use Firefox (version 98.0.2) to access Discord when using a web browser. 

I do not want Google Chrome on my computer, Ungoogled Chromium and Iridium don't like cooperating, and I barely touch Microsoft Edge due to problems that I have with that browser that are very unrelated to this issue. 

However, I do have the addon User-Agent Switcher and Manager to switch the user agent string to the latest Chrome version (User Agent String Used: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.7113.93 Safari/537.36) to test out the versions of DHT in Firefox that failed to log messages.

For DMs, messages are not being archived/logged in the following versions of DHT and methods of accessing Discord:
- DHT Desktop Script (Windows 10; DHT version 35.1) in the Discord Desktop App (Windows 10; Discord version 1.0.9004)
- Browser Console (DHT Console Script version 31a) in Firefox (Discord Stable 121719 (faa867d))
- - This method does appear to work when using the User-Agent Switcher and Manager add-on
- Browser Bookmarklet (DHT Bookmarklet version 31a) in Firefox (Discord Stable 121719 (faa867d))
- - This method does appear to work when using the User-Agent Switcher and Manager add-on

The versions of DHT that work for DMs are:
- Userscript method (version 31a) with Tampermonkey in Firefox
- Discord Console method (v31a) in the Discord Desktop App (Windows 10; Discord version 1.0.9004)
- Desktop DHT Script (version 35.1) in Firefox

For servers, messages are not being archived/logged in the following versions of DHT and methods of accessing Discord:
- Userscript (DHT Userscript version 31a) in Firefox (Discord Stable 121719 (faa867d))
- - Also failed when I used the User-Agent Switcher and Manager add-on
- Browser Bookmarklet (DHT Bookmarklet version 31a) in Firefox (Discord Stable 121719 (faa867d))
- - Also failed when I used the User-Agent Switcher and Manager add-on
- Browser Console (DHT Console Script version 31a) in Firefox (Discord Stable 121719 (faa867d))
- - Also failed when I used the User-Agent Switcher and Manager add-on

The only version that seems to be working for server messages is the Desktop DHT Script (version 35.1) when it is used in:
- The Discord Desktop App (Windows 10; Discord version 1.0.9004)
- Firefox (Discord Stable 121719 (faa867d))

I am not sure why DHT is not working in many of these instances. I hope that this extensive testing helps figure out the problem. I have included screenshots of the failed tests below to show the error messages that I have received while testing. Images also apply to any failed attempts with the User-Agent Switcher and Manager add-on.

![1](https://user-images.githubusercontent.com/19842754/161296912-258017c4-ba9e-4443-a6d7-ae826341364d.png)
![2](https://user-images.githubusercontent.com/19842754/161296917-9d922771-7ebc-446f-9def-ea59d9697ddf.png)
![3](https://user-images.githubusercontent.com/19842754/161296918-1417ab0c-bded-4950-93d2-f8294075d785.png)
![4](https://user-images.githubusercontent.com/19842754/161296920-2be300bb-3a52-4cdc-8c02-6f929e2b8b05.png)
![5](https://user-images.githubusercontent.com/19842754/161296923-002611c5-5536-4e87-92c1-5f2d2c35410f.png)
![6](https://user-images.githubusercontent.com/19842754/161296925-22517d7f-88e9-43d3-8b0e-cbbe8fdc63e4.png)

**Comment by chylex** [comment]
There is nothing in DHT that cares about user agent, the reason why some combinations of browsers / userscript managers don't work (or didn't work in the past, or may not work in the future) is because browsers / userscript managers are buggy, or simply behave in a way that breaks DHT, which is not something you can mask by changing a few words in a user agent.

Yesterday, Discord released an update (121601) which broke server tracking, and this got fixed in the app (35.1). Both DM and server tracking is working for me with app (35.1), when pasting the tracking script into both the Discord app (121601) or Firefox (122003).

The browser-only version of DHT cannot track servers because I didn't update it to support 121601 yet. It's completely separate from the app version, and personally I've not used the browser-only version for years, so I tend to forget about it. I can update it tomorrow.

**Comment by eduarcor** [comment]
Looking for the browser update, thanks!!

**Comment by chylex** [comment]
Released version v.31b

**Comment by princessbinas** [comment]
I am not sure why the desktop version isn't working for me in DMs. Do you have any recommendations that I should try to fix that?

**Comment by chylex** [comment]
Are there any errors in the browser console? The screenshot shows "Error" in the status bar, so the console should show what happened. Just be careful about posting any potentially private information that can appear in the console, like random-looking sequences of numbers and letters.
