### ISSUE TITLE
Is it possible to backup the messages of a guild?

### ISSUE THREAD

**Issue by mquinson** [chylex/Discord-History-Tracker#176]
Hello,

first of all, thanks for this great project!

I was wondering whether it's possible to also save the messages exchanged in a given guild. So far I only managed to save the personal messages, and each time I try to track a guild channel, I get the error `Error (Unknown Channel)` on the DHT status bar.

Thanks in advance,

**Comment by chylex** [comment]
Which version are you using?

**Comment by mquinson** [comment]
I'm using a full application that I downloaded from github, but I dont see no way to tell the version number that I'm using. It's on a Linux system. Discord is also the full app, not a browser tab.

thx

**Comment by mquinson** [comment]
I was obviously using v35 since v35.1 solves the issue for me. Sorry for the noise.

**Comment by chylex** [comment]
No worries. The version appears on the main menu if you don't have any database open.
