### ISSUE TITLE
langversion error when building the app-downloads branch

### ISSUE THREAD

**Issue by vielavlrs** [chylex/Discord-History-Tracker#179]
![1](https://user-images.githubusercontent.com/93360948/166147700-7e2b68a5-f55f-43ef-b990-a9d9d9d2b0da.PNG)
I'm trying to build the app-downloads to be able to download and link the attachments and images. However, I get this error whenever I run the build.bat in the app folder

**Comment by chylex** [comment]
I don't know what you think the state of the branch is, but there's a reason why it's in a branch and not officially released. If you're not a developer, you should not be building work-in-progress branches.
