### ISSUE TITLE
Issue where my profile is appearing over app controls

### ISSUE THREAD

**Issue by wallace28** [chylex/Discord-History-Tracker#181]
After the new Discord update, now for some reason my profile info and the mic/deafen options show over all the essential controls for tracking. Because of this, I can't actually hit any of the buttons so I basically can't use the program. Any advice?

![InkedChylex_LI](https://user-images.githubusercontent.com/105825676/169165894-796089b6-e852-4780-ada5-fbb46f1b456d.jpg)

**Comment by chylex** [comment]
I'll have to look into it tomorrow.

**Comment by chylex** [comment]
Update released.
