### ISSUE TITLE
Cannot merge with database

### ISSUE THREAD

**Issue by mwaitzman** [chylex/Discord-History-Tracker#184]
I just upgraded to v36 beta of the desktop app for linux x64, using the pre-compiled linux-x64 github release binary, and tried to merge with an older database. I get a pop-up window saying `Database <REDACTED> could not be opened:The current SynchronizationContext may not be used as a TaskScheduler.` This happens with both updated and non-updated databases. I'm on Arch Linux kernel version 5.17.9-arch1-1, and my packages are up to date. The log text in my terminal is 
```console
[ERROR] [DatabaseGui] System.InvalidOperationException: The current SynchronizationContext may not be used as a TaskScheduler.
[ERROR] [DatabaseGui]    at System.Threading.Tasks.SynchronizationContextTaskScheduler..ctor()
[ERROR] [DatabaseGui]    at System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext()
[ERROR] [DatabaseGui]    at DHT.Utils.Tasks.AsyncValueComputer`1.WithResultProcessor(Action`1 resultProcessor, TaskScheduler scheduler)
[ERROR] [DatabaseGui]    at DHT.Server.Database.Sqlite.SqliteDatabaseFile..ctor(String path, SqliteConnectionPool pool)
[ERROR] [DatabaseGui]    at DHT.Server.Database.Sqlite.SqliteDatabaseFile.OpenOrCreate(String path, Func`1 checkCanUpgradeSchemas)
[ERROR] [DatabaseGui]    at DHT.Desktop.Common.DatabaseGui.TryOpenOrCreateDatabaseFromPath(String path, Window window, Func`1 checkCanUpgradeDatabase)
```

**Comment by chylex** [comment]
Fixed in 133ec532d24e1f50ecf7eec5d0a7693a164b83f6, I might release a second beta later.
