### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'message' in undefined

### ISSUE THREAD

**Issue by Corrupt-Specturion** [chylex/Discord-History-Tracker#186]
In both release version 35.3 and 36.1, the tracker will stop at certain points in only one channel. There doesn't seem to be anything out of the ordinary when it stops. When I scroll up, it resumes tracking, but does not track the portion it stopped at.

[discordapp.com-1654497068995.log](https://github.com/chylex/Discord-History-Tracker/files/8842345/discordapp.com-1654497068995.log)
 
This is a log captured from the error message in the Discord client's console from one of the stopping points. All of the stopping points' console errors look to be about the same content-wise. No errors appear in the actual terminal used to run DHT, however.

I am running on Linux Mint Mate 20.2, kernel version 5.4.0-113-generic, using the latest Discord tar.gz client.

**Comment by chylex** [comment]
No idea what kind of message is causing this, but I can improve the error handling and 1) track messages near the error, and 2) show more information in the log.

**Comment by chylex** [comment]
Please try [this beta release](https://github.com/chylex/Discord-History-Tracker/releases/tag/v36.2.beta) and watch the browser console for errors. It should not stop tracking anymore when it encounters an error, but it will still print the error with more details that could help me understand why the error happens.

**Comment by Corrupt-Specturion** [comment]
[discord.com-1654562745952.log](https://github.com/chylex/Discord-History-Tracker/files/8849132/discord.com-1654562745952.log)

**Comment by chylex** [comment]
Can you please expand this part using the arrows?
```
{className: "message-XB61Zl", children: Array(5), onClick: ƒ}
```
Should be enough to expand down to two levels, i.e. click the arrow and then click any additional arrow that appears. Mind there might be personal information in the expanded parts, so please censor anything that includes names or long strings of numbers.

**Comment by Corrupt-Specturion** [comment]
[I wish there was an expand all button. I hope this is enough.](https://github.com/chylex/Discord-History-Tracker/files/8851725/discord.copy.com-1654592052802.log)

**Comment by chylex** [comment]
Looks like it's a server boost message, but if I look at server boost messages on my server DHT doesn't show any warnings. Could you please expand `children -> 3` like this?

![obrazek](https://user-images.githubusercontent.com/3685160/172468397-38ced5ce-7cce-4791-881b-027943ec9aea.png)

**Comment by Corrupt-Specturion** [comment]
![screenshot](https://user-images.githubusercontent.com/54480005/172488276-d9f727dc-384e-4e41-86c0-dfabaad05a75.png)

**Comment by chylex** [comment]
Interesting, I looked at server boost messages from 2019 to now, and none of them look like this. Regardless, DHT doesn't track boost messages so as long as they don't break tracking anymore, I'll consider it resolved.
