### ISSUE TITLE
Skips some messages or in-discord search reports wrong amount of messages?

### ISSUE THREAD

**Issue by RenWild** [chylex/Discord-History-Tracker#187]
Hello, I tried to download 2 channels. Data presented is a bit rounded but gives general idea.

First channel.
When I searched in discord with `in:<channel name>` it reported 5 millions messages. Tracker downloaded 4.98 million messages.

Second channel.
Discord search reported 50 thousands messages. Tracked downloaded 49930 messages. Then I tried to run the tracker again on the same channel and message amount (in tracker) didn't change.

Another thing that seems weird to me is that message amount in tracker tab "Viewer" (Will export ... out of ... messages) usually increases in 50s (so ends always with 50 or 00) but it occasionally increases in different amounts so that number can end with 9, 8, etc (in the same channel).

Discord used in firefox browser, tracker version is v36.2 (beta).

**Comment by chylex** [comment]
DHT doesn't track some types of messages that are counted in Discord search, for ex. boosts or pin notifications, so it's normal to have a non-multiple of 50. I don't know if that fully explains the discrepancies, or if there's any inaccuracies with the number from Discord search.

One thing you could try is to watch the number and pause whenever it increments by a suspicious number, then compare that area to see what's missing.

You can also set date and channel filters in both Discord search and the Viewer tab in the app. The app will tell you the number of messages that match the filter. You can start with a large range of dates, and narrow down the search until you get to a small enough range (for ex. a single day) that has a different amount of messages, then check those messages manually.

**Comment by RenWild** [comment]
Checked some suspicious increments and indeed they seem to fall in those categories (in my case I had: new user joined, thread started, message pinned).
Thanks.

**Comment by chylex** [comment]
Ah yea, thread started messages could be a lot. I thought DHT tracked those so I didn't mention it, but there are "thread started (created)" and "thread starter" messages, and DHT only tracks the latter.
