### ISSUE TITLE
Part of discord blocks the start tracking button

### ISSUE THREAD

**Issue by TonyEatWorld** [chylex/Discord-History-Tracker#188]
https://gyazo.com/e295ceac22fc88ca37c88f5323e6fbe6 Not really sure how to fix it, this has not happened before when using this. and yes... I did restart the app

**Comment by chylex** [comment]
Which version are you using?

**Comment by TonyEatWorld** [comment]
35.1 of the tracker app

**Comment by chylex** [comment]
Update to 35.3.

**Comment by princessbinas** [comment]
This issue is back again. 
![image](https://user-images.githubusercontent.com/19842754/178303799-5c9594b8-5f5a-441d-aa58-c08aec4d8cd8.png)

**Comment by chylex** [comment]
I'll wait for maybe a week and see if Discord changes their mind for the 5th time about how they want the main app area to be structured. If they don't, I'll fix it.

**Comment by chylex** [comment]
The latest version (37.1) has a better solution that should hopefully not break if Discord changes something again.
