### ISSUE TITLE
attachment not found

### ISSUE THREAD

**Issue by Butterfly-Dragon** [chylex/Discord-History-Tracker#190]
I made a backup of a category before deleting it so that people could access it from the viewer.

(it was a dead tabletop rpg play by chat)

The messages show up fine, but any dice roll or image shows up as "attachment not found".

Which, okay, i understand it cannot be loaded from discord since i literally deleted it.

But why it would not be visible in the viewer? i did save the attachment and everything. It is 230 MB of data in the DHT file.

**Comment by chylex** [comment]
Read the discussion for the attachment download beta, it's in bold text in the first sentence.

**Comment by Butterfly-Dragon** [comment]
uhm... apologies... the first paragraph of what? i checked the base page here https://github.com/chylex/Discord-History-Tracker and also the page here https://dht.chylex.com but i see no mention about anything of the sort? Am i missing something?

**Comment by chylex** [comment]
Either the discussion about attachment downloads https://github.com/chylex/Discord-History-Tracker/discussions/183 or the release notes for this version https://github.com/chylex/Discord-History-Tracker/releases/tag/v37

**Comment by Butterfly-Dragon** [comment]
Oooh!

Okay, sorry i just went into this an hour ago as i was saving yet another ended campaign after several months (almost a year) after the last time i used DHT. SO i was definitively out of the loop.

And after writing the above, from your response, i searched around and saw a py file which read `To view the archive with downloaded files, you must place the viewer in the same folder as the archive file and download folder.` so i was trying to now understand how to use that python file from the code.

I see that instead i just have to wait and have faith. Sorry, as i thought i was at fault for being too out of the loop.

Fair enough, apologies.

I will just make a copy of the archive database to use when i have time to check here again.

Meanwhile i just re-joined your pareon. I had no clue why i was in that patreon for (it does not really mention your work on DHT) so i had deleted myself from it a couple of weeks ago, i am now back in.

**Comment by chylex** [comment]
No worries.

The python script is for the legacy archives, which are from the browser-only version of DHT. It doesn't work on archives from the app. When I split the browser-only and app versions into completely separate branches, I forgot to remove the script from the main branch.

I was planning to support viewing downloaded attachments earlier, but I've been busy with work and other projects.

Today's Discord update broke DHT so I released the update as-is. I figured it'd be useful to have the ability to download attachments even if you can't view them yet, since it's always possible for attachments to get deleted.

**Comment by Butterfly-Dragon** [comment]
Exactly my thought, so, while for now i will keep the dht archive saved i will know i will need (at some point in the future) to repackage the viewer.

In any case this is super useful, thanks.

By the way, do i have to enable the threads for them to be downloaded in the DHT or does DHT do it on its own?

**Comment by chylex** [comment]
Threads are basically channels, you have to click the thread in the channel list and track it as any other channel. It doesn't work in the split-screen mode though, where you see both the original channel with the thread on the right side.

**Comment by Butterfly-Dragon** [comment]
so if they are archived they will not be explored?

**Comment by chylex** [comment]
If a thread is archived, it will appear as a separate channel in the viewer.

**Comment by Butterfly-Dragon** [comment]
Apologies for being unclear, i was talking about the function that goes to the next channel when it reaches the end of the current one.

But i guess we are going very off topic here and i can just run DHT on the current live campaign to see what happens when it meets a thread

**Comment by chylex** [comment]
I checked and it doesn't switch to thread channels, it could be improved. On the other hand, this functionality is broken by updates very often and tends to be very annoying to fix, so I try not to touch it.

**Comment by Butterfly-Dragon** [comment]
eh, i thought it could just... when it finds a thread link (which i have never checked, so i do not know how that link works "from the inside") it would follow it then go back to the main thread it left and do the same again next time it found one such link.

But then the "simplest" solution is simple only because one is looking at it from the outside without any knowledge of how it works.
