### ISSUE TITLE
User Reactions capture

### ISSUE THREAD

**Issue by AnthonyG04** [chylex/Discord-History-Tracker#191]

**Comment by TheTechRobo** [comment]
Please provide an explanation of this issue. "User Reactions capture" could be referring to a myriad of things.

**Comment by AnthonyG04** [comment]
I have an idea of adding in the capture of the lists of reactions to messages. Which is currently unviewable.

**Comment by chylex** [comment]
I have no idea what you mean.

**Comment by AnthonyG04** [comment]
![image](https://user-images.githubusercontent.com/73410258/174485576-a4270233-af29-4f74-a962-f9d13fabca05.png)

**Comment by chylex** [comment]
The message data DHT sees only includes the number of reactions, I don't know where to get the list of users from. From what I can tell, Discord only loads the list of users when you open the dialog and start clicking through all the emoji, which is not something DHT is going to simulate.
