### ISSUE TITLE
Can't log the very beginning of conversations

### ISSUE THREAD

**Issue by Danfun64** [chylex/Discord-History-Tracker#193]
Not sure why I haven't mentioned this before, but usually when DHT gets close to the top of a Discord conversation, it gives "Reached end" even if there are like a few dozen messages sent between the actual beginning and where it stopped. This is perhaps most annoying in extremely short conversations which aren't logged at all.

**Comment by TheTechRobo** [comment]
It'll still see the messages unless there's more pagination. Are they not shown in the viewer?

**Comment by Danfun64** [comment]
Actually, I think I was in the wrong. The software genuinely used to have that problem a while back, and I assumed that it still had it since it appeared the same at first glance (the software would pause before it got to the top). If I ever bump into the problem again I'll let you know.
