### ISSUE TITLE
Unable to run Linux version on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by Andrej-VB** [chylex/Discord-History-Tracker#197]
Similarly to #171, double-clicking the extracted executable file seems to have no effect

**Comment by TheTechRobo** [comment]
Have you tried this?

```
chmod u+x <PATH TO FILE>
```

**Comment by Andrej-VB** [comment]
Just tried it, unfortunately nothing has changed. Also tried adding .run and .bin to the end of the file's name. But running those seems to be the same - nothing happening.

**Comment by chylex** [comment]
I don't have Ubuntu but I tried Fedora, the permissions are set correctly and double-clicking works fine. Try running DHT via terminal to see if there's any crashes.

**Comment by Andrej-VB** [comment]
Silly of me not to immediately realise there's another part of this

> ```
> chmod u+x <PATH TO FILE>
> ```

which is:
`./<PATH TO FILE>`

The program then actually runs in the terminal, after which there's this response:

_No usable version of libssl was found
Aborted (core dumped)_

I've then tried to install openssl like so:
```
wget openssl.org/source/openssl-1.1.1o.tar.gz
tar -xvzf openssl-1.1.1o.tar.gz
cd openssl-1.1.1o
./config
```

Running in terminal afterwards gives the same error. I will try installing other versions of openssl or upgrading .NET core and report back when successful. If anyone has a clue on what to try first please let me know.

**Comment by chylex** [comment]
Are you using the Linux version or the generic "Other" one? The Linux version is self-contained, the .NET runtime is already included in it.

**Comment by Andrej-VB** [comment]
Trying with the Linux version. Didn't use the Other too much

**Comment by chylex** [comment]
I don't think `./config` is enough to actually install openssl, see https://github.com/dotnet/core/issues/4749#issuecomment-1200245422

**Comment by Andrej-VB** [comment]
Thank you! 
This worked like a charm. 

By default Ubuntu 22.04 comes with openssl version 3. After installing the 1.1.1c per instructions in this [comment](https://github.com/dotnet/core/issues/4749#issuecomment-1200245422), rebooting, and installing again, I've managed to run the DHT through terminal with

```
chmod a+x <PATH TO FILE>
./<PATH TO FILE>
```


You can check what version of openssl is running with
`openssl version -v `

Once the output was _OpenSSL 1.1.1c  28 May 2019_, DHT ran successfully

PS. 
If for some reason there's an error with make  _make: *** [all] Error 2_, it goes away after` sudo apt install libfl-dev`
