### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by AirplanegoBrr** [chylex/Discord-History-Tracker#199]
This might have some features that have been requested if so sorry!

1. Server folder. Channels and stuff will be put in the folder of the server they belong to.
2. Resend all messages in X channel (server use ONLY) using a webhook or bot (self hosted bot), resend all messages.
3. Drag and drop to open a DHT file (I was told this was a good idea)
4. Custom self hosted bot to auto add to the DB 
5. Option to pick what kind of database type to use (JSON, MySQL, etc)
6. Betterdiscord plugin w toggle to auto-update DB. (would also be nice to see this in the tracking script)
7. Maybe some sort of nodejs (or any other lang) module to scan the DB and add to it? (it would be nice if it had a special flag on each message to see if it's from nodejs or from the tracking script)
8. Mutiaccount support. Make it so each person is linked to X account (same with servers?)

I know some of these features I'm requesting would be hard to implement but it would be nice to see people's thoughts
If you want to add to these features feel free to comment on them!

**Comment by TheTechRobo** [comment]
> - Custom self hosted bot to auto add to the DB
> - Betterdiscord plugin w toggle to auto-update DB. (would also be nice to see this in the tracking script)
> - Maybe some sort of nodejs (or any other lang) module to scan the DB and add to it? (it would be nice if it had a special flag on each message to see if it's from nodejs or from the tracking script)

What do you mean?

**Comment by chylex** [comment]
> 1. Server folder. Channels and stuff will be put in the folder of the server they belong to.

Could be nice, I can accept a PR but only if it's easy to implement and maintain; especially in the tracking script. Remember that I'll have to fix it every time Discord changes.

> 3. Drag and drop to open a DHT file (I was told this was a good idea)

Planned.

The rest is out of scope of this project. External integrations w/ Discord plugins or bots can be done without my involvement.

---

If someone is interested in PR-ing `1.`, they can open a discussion thread to discuss the implementation. There's already an issue open for `3.` and the rest is not planned, so I'm closing this issue.
