### ISSUE TITLE
Feature request: Allow downloading of emotes, stickers and avatars

### ISSUE THREAD

**Issue by Freigeist** [chylex/Discord-History-Tracker#200]
The reason behind this feature request is simple: It would allow a true offline archive. Servers and Users get deleted etc. and it would be nice to still be able to view the stored messages how they were supposed to be. Also good in a case where Discord goes down/is unreachable for whatever reason.

**Comment by TheTechRobo** [comment]
I'm not sure this is in-scope for DHT (but the developer would have to answer that). It would definitely be nice to at least have the identifiers necessary to make a URL, so you can extract URLs from the archive.

**Comment by chylex** [comment]
It should be possible, but first I need to come up with some way to collect downloadable URLs from all parts of the archive. I will need to do that to allow downloading embeds anyway.

**Comment by chylex** [comment]
Currently, embeds linking to Discord CDN, avatars, and reaction emoji will be downloaded. Non-Discord embeds, emoji in messages, possibly stickers and other things will come later.
