### ISSUE TITLE
Discord History Tracker not accepting .dht files

### ISSUE THREAD

**Issue by andrewv14** [chylex/Discord-History-Tracker#201]
Going from https://dht.chylex.com/browser-only/build/viewer.html and uploading .dht files. The response gets:

Could not parse 'FILENAME.dht', see console for details.

Anyone run into this before?

**Comment by TheTechRobo** [comment]
As the URL states, **that viewer is for the browser version of DHT only**. The viewer is built into the desktop app.

**Comment by andrewv14** [comment]
Thanks for the response! I didn't mention it in my original post, we put the .dht files on a big server that people would hypothetically download and view. It's a big ask to ask a server of 600+ people to download the desktop app just to view these files. Is there a way to use the browser version to load those .dht files?

**Comment by chylex** [comment]
You can save a viewer in the app and upload that.

**Comment by andrewv14** [comment]
> You can save a viewer in the app and upload that.

Chylex, what do you mean by that?

**Comment by chylex** [comment]
There's a "Save Viewer" button in the "Viewer" tab in the app, idk how to make it clearer.

**Comment by andrewv14** [comment]
That worked! In the overall process that was the step I was missing. Thanks so much.

**Comment by chylex** [comment]
Cool, I'm closing the issue as answered.
