### ISSUE TITLE
Feature request: Auto backup

### ISSUE THREAD

**Issue by Aeternus185** [chylex/Discord-History-Tracker#203]
Keep the discord tracker open and have all chats automatically backed up.
If our account is banned without warning we would already have a full backup.

**Comment by TheTechRobo** [comment]
Can't you just manually run through each server?

**Comment by Aeternus185** [comment]
The idea is to not have to do it, just leave the program in the background and use discord as usual.

**Comment by TheTechRobo** [comment]
> and use discord as usual.

That won't happen unless you have multiple instances of Discord open, because the app can only show one page at once.

**Comment by chylex** [comment]
DHT can only track what's currently visible, and the current ability to automatically switch to the next channels is already a pain to maintain, so switching between servers won't happen.
