### ISSUE TITLE
Error (Unknown channel)

### ISSUE THREAD

**Issue by IDKhowToScript** [chylex/Discord-History-Tracker#204]
Console log:
Error retrieving selected channel. TypeError: Cannot read properties of null (reading 'innerText')
    at DISCORD.getSelectedChannel (<anonymous>:16:3326)
    at onMessagesUpdated (<anonymous>:181:24)
    at <anonymous>:226:4
    at Object.setIsTracking (<anonymous>:96:1274)
    at HTMLButtonElement.<anonymous> (<anonymous>:54:399)
    at HTMLButtonElement.r (a6a298b843663048d662.js:145:559)

using chrome 105.0.5195.127 

Tried: Restarting DHT
Clearing browser cache
Switching application (web/app)
Trying different server
Use another database
Restarting PC

**Comment by TheRealUkey** [comment]
Having the same issue for the first time. Tried to:
- Use another database
- Switch to app instead of browser
- Try different server and channels

Seems like initially it scrapes the first page and getting the error once needed to scroll.

**Comment by chylex** [comment]
Released an update for the desktop app, I'll deal with the browser-only version later.

**Comment by FireMario211** [comment]
The issue is because of the querySelector using `nav header h1[class*='name-']`, as it's considered `null`, rewriting it to check if it's in a guild, and iterating through the children of `nav header [class*='headerContent-']` fixes this (Based from the Desktop ver).
```js
for (const child of r(document.querySelector("nav header [class*='headerContent-']")).children) {
    if (child && child.props && child.props.guild) {
        guild = child.props.guild;
        break
    }
}
```

**Comment by chylex** [comment]
I will update the browser-only version tommorow. Fixing code is the easy part, it's the testing + build + deployment + wiki that are the most tedious and time-consuming parts of updating the browser-only version (and honestly, automating the process is not really worth it, since the browser-only version is only getting occasional critical fixes).
