### ISSUE TITLE
Error (Unknown Channel) 

### ISSUE THREAD

**Issue by AnthonyG04** [chylex/Discord-History-Tracker#205]
I have been having this issue on the windows program version of Discord History Tracker, where it cannot track messages, and I get an error that says "Error (Unknown Channel)".

**Comment by TheTechRobo** [comment]
Update to the latest version

**Comment by AnthonyG04** [comment]
Thank you! I wasn't aware that it hadn't been updated. I think seeing an auto-updater in a future update for DHT would be very beneficial.

**Comment by TheTechRobo** [comment]
> I think seeing an auto-updater in a future update for DHT would be very beneficial.

#165

**Comment by chylex** [comment]
Duplicate of #204.
