### ISSUE TITLE
exits with "No usable version of libssl was found"

### ISSUE THREAD

**Issue by woozalia** [chylex/Discord-History-Tracker#208]
$ ./DiscordHistoryTracker
> No usable version of libssl was found
> Aborted (core dumped)

I don't know where the core-dump is; it doesn't seem to be in `/var/log`.

* **OS:** Linux Mint 21.1 Vera 64-bit
* **Kernel:** Linux 5.15.0-57-generic x86_64
* **Desktop:** MATE 1.26.0

**Comment by chylex** [comment]
Try https://github.com/dotnet/core/issues/4749#issuecomment-1200245422

**Comment by woozalia** [comment]
> Try https://github.com/dotnet/core/issues/4749#issuecomment-1200245422

I was able to compile/make that, but I still get the same error from DHT. I assume DHT is somehow not finding the compiled library. Any suggestions? Is there a specific lib file it's looking for, that I should maybe link to the compiled one? (Note: the compiled lib file does not appear to be in `/usr/local/lib`, despite what the instructions say.)

**Comment by chylex** [comment]
There was a previous issue that followed the instructions and made it work, see https://github.com/chylex/Discord-History-Tracker/issues/197#issuecomment-1201414260 if there's anything that can help.

**Comment by chylex** [comment]
When I have time I will update DHT to a newer .NET version that supports OpenSSL 3.

**Comment by chylex** [comment]
The app was updated to the latest .NET a while ago, so this should be resolved.
