### ISSUE TITLE
The viewer page for Discord-History-Tracker is not working.

### ISSUE THREAD

**Issue by seroihub** [chylex/Discord-History-Tracker#213]
I have downloaded 7 .txt files from Discord Tracking.
I loaded the files from the viewer page (https://dht.chylex.com/browser-only/build/viewer.html) as described in the documentation, but the files are not uploaded to the page.
Is there any solution?

**Comment by chylex** [comment]
Did you download the viewer page as the instructions say? Which browser and version are you using?

**Comment by seroihub** [comment]
I'm using the Chrome browser
The version is 112.0.5615.49 arm64
My OS is MAC.
I cloned this https://github.com/chylex/Discord-History-Tracker/tree/master-browser-only repository and ran the python build in vs code.
Then, I entered the generated track.js file into the Web DevTools console window to download the .txt file.
Then, I uploaded the downloaded .txt file from the viewer page, but it didn't upload.
Is there something wrong with the process?

**Comment by chylex** [comment]
From the comment I don't know the answer to whether you downloaded the viewer. There's no need to use vs code to use DHT, but if you're using vs code to build the tracker in the first place then why not also build the viewer?

**Comment by seroihub** [comment]
https://dht.chylex.com/browser-only/build/viewer.html
이 링크는 그럼 무엇인가요??

**Comment by chylex** [comment]
You're supposed to download https://dht.chylex.com/browser-only/build/viewer.html and use it offline. If that still doesn't work, check if the browser console shows any errors.
