### ISSUE TITLE
Bugs & crash on the attatchments tab

### ISSUE THREAD

**Issue by AstroOrbis** [chylex/Discord-History-Tracker#214]
![image](https://github.com/chylex/Discord-History-Tracker/assets/65419194/9ddfb90f-4f79-498f-af47-c6059d61ee9a)

All of the attachment statuses are 0 with a null size, and whenever I hit **`Start Downloading`**. the app freezes then crashes. Tracking messages works normally, and tracking a message with an attachment will +1 the counter.

Is anyone else facing this issue?

**Comment by chylex** [comment]
Can you post the crash report? Easiest way should be if you launch DHT from a terminal and it should show up there when the app crashes; on Windows there might also be crash reports in the event viewer but I'm not 100% sure how to get what I need out of them.

**Comment by AstroOrbis** [comment]
I can only find these two errors in Event Viewer:

```
Application: DiscordHistoryTracker.exe
CoreCLR Version: 5.0.1722.21314
.NET Version: 5.0.17
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at DHT.Server.Database.Sqlite.SqliteDatabaseFile.GetEnqueuedDownloadItems(Int32 count)
   at DHT.Server.Download.BackgroundDownloadThread.ThreadInstance.FillQueue(IDatabaseFile db, ConcurrentQueue`1 queue, CancellationToken cancellationToken)
   at DHT.Server.Download.BackgroundDownloadThread.ThreadInstance.Work(Object obj)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

```
Faulting application name: DiscordHistoryTracker.exe, version: 37.2.0.0, time stamp: 0x62577ba6
Faulting module name: KERNELBASE.dll, version: 10.0.25381.1, time stamp: 0xd8c2ff16
Exception code: 0xe0434352
Fault offset: 0x000000000003404c
Faulting process id: 0x0xA8A4
Faulting application start time: 0x0x1D99B1CE944DDC8
Faulting application path: C:\Users\Astro\Files\Apps\DiscordHistoryTracker.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 51754c1a-30b2-4ede-b6b8-100dd9531de5
Faulting package full name: 
Faulting package-relative application ID: 
```

The main offender seems to be  SQLite Error 11: 'database disk image is malformed'`. Is there a way I can recover it without losing any of the data?

**Comment by chylex** [comment]
Not without losing any of the data, but you can try to recover as much of it as possible by downloading the "command-line shell" for SQLite from https://www.sqlite.org/download.html and following section 2 of this guide: https://www.sqlite.org/recovery.html

If you have something important and cannot afford any data loss at all, you need to have backups.

**Comment by AstroOrbis** [comment]
Following the instructions at section 2 of the guide didn't work because of an out of memory error (I have 64 gigs of ram and the file was ~30 gigs), but following the instructions at [this](https://stackoverflow.com/a/58157161/17029825) stackoverflow answer worked like a charm:

```
.open Discord.dht
.clone DiscordFix.dht
```
then DiscordFix.dht should be the correct file.
