### ISSUE TITLE
Support display names?

### ISSUE THREAD

**Issue by TheTechRobo** [chylex/Discord-History-Tracker#216]
Right now it shows their account name which isnt that bad but could be better.

**Comment by peepincreepin** [comment]
+1 from me for this. If it could show the user's role colour as well, that would be fantastic, but I suspect that might be impossible. But either way, even the display name on its own would be amazing.

**Comment by darkpc2** [comment]
I agree with this as well. I use a bot for roleplaying and it uses Display Names for the aliases but so far It only saves the first Name for the entire chat archives as it stands right now

**Comment by chylex** [comment]
Display names would only be supported with https://github.com/chylex/Discord-History-Tracker/discussions/218 which is not happening anytime soon, probably not this year.

**Comment by chylex** [comment]
I realized it's unclear what the issue is about. I will be adding support for display names as opposed to usernames, but I will not be currently adding support for per-message names that bots use.

**Comment by TheTechRobo** [comment]
That was indeed what I meant when creating the issue. Thanks for implementing it!
