### ISSUE TITLE
Better reply handling??

### ISSUE THREAD

**Issue by FlashlightET** [chylex/Discord-History-Tracker#217]
Current one is less than optimal and very hard to process. Why is it stored as its own array instead of being part of the message array? E.g. message = message id, sender id, channel id, text, timestamp, **replied to id** which can be none if its not replying.

My brain cannot even begin to comprehend how to get all messages containing a specific string by a specific user, and get the user id of the message they are replying to (bot responding 'correct' or 'incorrect' to a user and getting said user's user id)

**Comment by chylex** [comment]
I don't know what array you're talking about. In the database, they're stored as a standard 1..0-1 relationship using a separate table. A column mostly filled with nulls is a waste of space. If you need your results to have a nullable column based on the contents of another table, use a LEFT JOIN.
