### ISSUE TITLE
empty messages

### ISSUE THREAD

**Issue by Shoro2** [chylex/Discord-History-Tracker#22]
Heya,

1st of all, i rly love your tool, but i want to use ur tool to log a game result channel to create statistics for these games.
The game results are posted by a bot on game end. When i download the log and parse it into the viewer, i only see the name of the bot but not the message itself.
Viewer: [https://imgur.com/a/60x5I](url)
Discord Channel: [https://imgur.com/a/JzW3H](url)

When i disable link preview on discord, the messages by the bot are like in the viewer:
[https://imgur.com/a/SAZuq](url)

How can i log these messages?

**Comment by chylex** [comment]
I'll look into it for the next update.

**Comment by Shoro2** [comment]
Ah i noticed that these messages are webhooks

**Comment by Escaflownevan** [comment]
Do you know a date for webhooks update? Have the same problem.. Need it badly :)

**Comment by chylex** [comment]
Don't know, been busy with university, I should be all done next week though.

**Comment by Escaflownevan** [comment]
Next week would Be Vera nice! Ty for Fast answer

**Comment by Escaflownevan** [comment]
*very

**Comment by Shoro2** [comment]
If it helps you:
I set up a bot to log the channel and i get the content from the message.embeds.fields[i]

**Comment by chylex** [comment]
So... I can easily make webhooks and certain bot messages work, however some bot messages have complicated formatting, which is something I don't want to deal with right now.
