### ISSUE TITLE
Feature Request: Sentry mode

### ISSUE THREAD

**Issue by potato03kth** [chylex/Discord-History-Tracker#221]
Sometimes, when you use DHT, you need the following functions.
- The function to arrest people who post problematic posts on the server and erase them again in a very short time.
- The function to arrest people who post problematic posts on the server and correct them in a very short time.
- Or just the ability to log and track every part of the server in real time.

I suggest Sentry Mode as a function to solve this situation.
I want to add the ability to track the most recent posts (I don't think you'll need more than 100 for general use) every second so that DHT knows everything about the server.
Of course, we can do this by implementing an existing bot or (e.g., AltDentifier) DHT auto-renewal server, but I don't think it would be bad to add it as DHT's own function

and also, Thank you for your continued service to the cause.

**Comment by TheTechRobo** [comment]
You can disable autoscroll and leave it running

**Comment by potato03kth** [comment]
Oh my.....

**Comment by chylex** [comment]
You will want a server bot for that, DHT can only see what the client sees so it's impossible for DHT to know what's happening in every channel.

It might be interesting to have a feature that automatically switches to a channel that has unread notifications and catches up with unread messages, if that can be done reliably, but there are limits to how fast DHT can perform actions and it likely wouldn't be able to keep up with massive servers.
