### ISSUE TITLE
Enabling Ctrl-Shift-I on via DHT Mac Desktop App doesn't open console anymore

### ISSUE THREAD

**Issue by colobus0lather** [chylex/Discord-History-Tracker#225]
Is it possible a recent discord update has blocked the workaround to open the developer console?

**Comment by TheTechRobo** [comment]
The desktop app has a button somewhere to enable Ctrl-Shift-I.

**Comment by chylex** [comment]
Do you mean it used to work for you and suddenly stopped?

**Comment by chylex** [comment]
Closing due to no response and likely not being an issue with DHT.
