### ISSUE TITLE
"Cannot see any messages." prompt blocks use

### ISSUE THREAD

**Issue by V-plus7** [chylex/Discord-History-Tracker#226]
Using Discord HIstory Tracker on either the desktop app or browser, a pop-up appears with "Cannot see any messages" regardless of which server I try to save. I've even tried it on a fresh Windows 10 VM and it still appears. The console gives me these errors:

```
28cbbf53e79cf7167475.js:1 [DHT] Error retrieving messages. TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at DISCORD.getMessageElements (<anonymous>:16:262)
    at DISCORD.getMessages (<anonymous>:16:1827)
    at <anonymous>:216:29
    at Object.setIsTracking (<anonymous>:96:1274)
    at HTMLButtonElement.<anonymous> (<anonymous>:54:399)
``` 
I don't know if this is an issue on my end or if a Discord update caused it.

**Comment by Kingistel** [comment]
Seconded, and really hope for a speedy fix. The error is exactly the same. This is an unpleasant situation when you need to save a branch urgently, but there is no way to do it.

**Comment by Facsimilii** [comment]
Can confirm, I'm also seeing this. I have tried current archives, tried creating a new archive, and even tried Option #2 (Browser/Discord Console) just to see if I could get around the issue, with no luck. Also on Windows 10 here.

**Comment by StoneIron02** [comment]
The same thing happens to me.

**Comment by Imjustarandomlol32** [comment]
I think it's the new Discord update, correct me if I'm wrong.

**Comment by chylex** [comment]
Should have an update ready in a few hours or tomorrow.

**Comment by Imjustarandomlol32** [comment]
Is there any updates?

**Comment by chylex** [comment]
The desktop app is updated, the browser-only version will be later.

**Comment by helloworld-me** [comment]
Now, when I enter "Ctrl+Shift+I" in the Discord desktop app, it causes the program to restart - and no matter how many times I login and hit "Ctrl+Shift+I" the same thing happens.

Is this a bug in the new update or is this a setting I am messing up?

**Comment by Facsimilii** [comment]
I can confirm that with the new update I'm experiencing no issues. Are you waiting for the code window to fully load before you paste in? I've had problems before where, if I paste too quickly, the whole thing just stops working. (This is just a guess, I'm not a programmer so I have no real idea, I'm just a tech support monkey in my day job.)

**Comment by chylex** [comment]
I've had the Discord app restart and forcibly log me out at random when the Dev Tools are open, I would recommend using a browser.

**Comment by helloworld-me** [comment]
Seems like a random bug, because I did everything the same a dozen times or so and suddenly one of the times it started working. So, it's working for me now - that's my update.

PS: Thank you Chylex for creating this program and for diligently maintaining it for so long (which I know involves dealing with bozos like me! lol)
