### ISSUE TITLE
Issue with tracker after latest Discord update "Cannot See Any Messages."

### ISSUE THREAD

**Issue by OpMegs** [chylex/Discord-History-Tracker#228]
Had this update just after the most recent Discord update on November 1st.

![diserror](https://github.com/chylex/Discord-History-Tracker/assets/31227533/89586d32-cc62-47ea-895f-58d3533ae385)

Pops up in console when trying to begin tracking

**Comment by TheTechRobo** [comment]
Have you updated to the latest version of the app? (I don't think the browser-only version has been updated yet.)

**Comment by OpMegs** [comment]
Ah, I missed the update a few days ago. That fixed it. Thanks!
