### ISSUE TITLE
Browser Extension version issue: "The selected channel is not visible in the channel list."

### ISSUE THREAD

**Issue by RydenOpsaidoun** [chylex/Discord-History-Tracker#230]
I've been trying to log comments for the past month, but DHT keeps running into an error that "The selected channel is not visible in the channel list.". I use Opera, Brave, and Tampermonkey and I tried over and over again to update the script. I keep reading that there's a v38 version but it thinks it's still updated with v31e. I keep seeing the red notification on my Tampermonkey extension icon which should tell me there's an update, but nothing has changed after I tried to updated everything.

I ended up not being able to record critical comments after drama occurred on my servers and there was evidence deleted so I couldn't prove anything to the mods.

Is there a better way to update DHT or does it just not function on browser versions anymore?

**Comment by TheTechRobo** [comment]
I don't think the browser-based version has been updated yet, but the desktop app does work (and you can paste its tracking script into a browser).

**Comment by chylex** [comment]
The userscript/bookmarklet (browser-only) version of DHT was replaced by a desktop app a few years ago and that's the recommended way to use it. The browser-only version only gets occasional updates to fix tracking, it has not been updated for the latest Discord version yet.

**Comment by OpatrilPeter** [comment]
I've had a need for the browser only version and made a stopgap solution that handles at least the case of single channel download by frankensteining the script from master branch with bits from browser-only version.

It requires some manual effort, but if someone would find that case useful, I've posted it [here](https://github.com/OpatrilPeter/discord-history-tracker-hotfix).

**Comment by andrewv14** [comment]
@chylex do you have an idea as to when the browser-only version will be updated? I have the same issue as OP and I'd like to be able to archive soon. Worst case I can do the desktop version but would prefer to do the browser-only. Let me know - thanks!

**Comment by chylex** [comment]
No ETA. If you have the option to use the desktop version, I would recommend just using that now; eventually the browser-only version will go away entirely because it's bad in many ways and I don't enjoy spending my time on it.

**Comment by will-ca** [comment]
I think I've fixed the browser version, and also refactored it so it can be maintained with only minimal effort going forwards. Will clean up and PR later I think.

**Comment by chylex** [comment]
Backporting the fix is the easy part, I can do that in a few seconds; every update of the browser-only version also requires testing, rebuilding and uploading the website, updating release notes, updating links to old versions, and re-checking that the update applied correctly.

**Comment by will-ca** [comment]
> If your refactor updates the syntax to match the app's tracker, that will definitely be a welcome PR.

That's the idea, yeah. Actually it goes even further and rebases the browser version on the desktop `git` history, so future changes can simply be automatically merged instead of backported, and to reduce/eliminate separate testing by using the exact same `discord.js`/`dom.js`.

Since you mentioned it, I've also tried to make the website, release notes, and links to old versions lower/zero maintenance.
