### ISSUE TITLE
Duplicate attachments get downloaded when tracked over

### ISSUE THREAD

**Issue by Corrupt-Specturion** [chylex/Discord-History-Tracker#231]
When attachments that have already been downloaded get tracked over, they are added to the download queue and downloaded as duplicate attachments. I assume this is because of the new data appended to the end of attachment URLs.

Discord History Tracker v38, Linux Mint MATE 20.2, Linux 5.4.0-166-generic x86_64 Kernel

**Comment by chylex** [comment]
Yep, known issue, essentially duplicate of #223 so closing in favor of that.
