### ISSUE TITLE
'Waiting' issue

### ISSUE THREAD

**Issue by D-Palz** [chylex/Discord-History-Tracker#233]
When tracking script is pasted and i try to start the tracking an error message pops up saying 'Cannot see any messages' although there are messages within the discord channel.

**Comment by will-ca** [comment]
Latest desktop app, latest `master-browser-only`, and my refactor rebasing `master-browser-only` onto `master` all still work for me. We'll see if Discord pushes an update to break it later I guess.

**Comment by D-Palz** [comment]
> Which version of DHT are you using?

**Comment by D-Palz** [comment]
How do i check which version of DHT im using. In terms of the Avalonia application it states its the 0.10 version.

**Comment by D-Palz** [comment]
<img width="969" alt="Screenshot 2023-11-22 at 21 37 39" src="https://github.com/chylex/Discord-History-Tracker/assets/151744826/69fe3113-90a4-41b0-a2d2-9f40c20eb073">

**Comment by D-Palz** [comment]
![Uploading Screenshot 2023-11-22 at 21.37.39.png…]()

**Comment by D-Palz** [comment]
<img width="969" alt="Screenshot 2023-11-22 at 21 37 39" src="https://github.com/chylex/Discord-History-Tracker/assets/151744826/e46b2ceb-f95a-4386-a0c3-1cd507a8646a">

**Comment by will-ca** [comment]
@D-Palz A change to Discord broke `v37` around a month ago I believe. See #226, and the [Release Notes](https://github.com/chylex/Discord-History-Tracker/releases). I think you're supposed to update to `v38`, and it should be able to open the same database file. Make a backup of the database first if you're worried about it.

Note I am not the DHT developer.

**Comment by chylex** [comment]
You need to use the latest version. If your database file is important, you need to have backups of it regardless because your computer could stop working at any moment.

**Comment by TiffanyNeat** [comment]
This issue is appearing again on the latest update to Discord.
