### ISSUE TITLE
"Do Nothing" option broken/different on Browser?

### ISSUE THREAD

**Issue by will-ca** [chylex/Discord-History-Tracker#234]
If you select "Do Nothing" for "After reaching a previously saved message" in the browser-only version, DHT stops auto-scrolling at that point, allowing you to manually continue scrolling or manually switch to another channel.

With the Desktop version, DHT instead just keeps scrolling on.

Maybe this is the intended behavior? Does "Do Nothing" mean:

1. Stop doing the previous action, and wait, like the browser version, OR…
2. Proceed as if nothing has changed, like the desktop version?

Not really much of an issue either way I suppose, provided it's working as intended. Just something I noticed (and was confused by because I wasn't sure whether it was my code breaking something).

**Comment by chylex** [comment]
"Do Nothing" means "don't touch anything", so it's intended to continue tracking with current settings (autoscroll on/off). So according to what you said, it's broken in the browser-only version.

**Comment by will-ca** [comment]
Cool. Well, #236 fixes it for the browser version by using the desktop `bootstrap.js`, then.
