### ISSUE TITLE
New Version of Tracker for Mac OS Displaying As TextEdit files and not Unix Executable

### ISSUE THREAD

**Issue by Honovi1** [chylex/Discord-History-Tracker#238]
Hello I'm very new here and I apologize if I am not going about this correctly, I have enjoyed using this tracker for a long time and appreciate all the good work you do on it. I haven't had any problems until the recent update where the app will not launch in terminal because the file type is for some reason a text edit document. Despite dragging and dropping it into terminal and trying to force it to run in other means it will not launch. The older version launches well but because of the discord update it will not detect messages. Hopefully this isn't too much work to fix, thank you!  I have attached a comparison to the file types from the old version to the new version:
<img width="1051" alt="File Comparison" src="https://github.com/chylex/Discord-History-Tracker/assets/152006368/22de6172-fcce-4be5-8b94-c66a3aef8a02">

**Comment by TheTechRobo** [comment]
Try going into the folder that it is in and running `chmod +x DiscordHistoryTracker`. (Or type `chmod +x ` and then drag the file onto the terminal.)

**Comment by chylex** [comment]
Re-uploaded corrected zip files.
