### ISSUE TITLE
Cannot see any messages on newest update of Discord

### ISSUE THREAD

**Issue by TiffanyNeat** [chylex/Discord-History-Tracker#240]
When clicking the Start Tracking button, a pop-up saying "no messages could be found" appears. I'm running off the Linux release of DiscordHistoryTracker, using the Discord flatpak w/ BetterDiscord integrated.

**Comment by chylex** [comment]
Confirmed the issue, I don't know when I'll have time to release an update.

**Comment by TiffanyNeat** [comment]
> Confirmed the issue, I don't know when I'll have time to release an update.

A confirmation was all I need, had the idea that maybe I reinstalled BetterDiscord wrong or it's an 'exclusive to Linux' issue but I assume you're saying it's on elsewhere OSes too?

Good luck with the update-- last I checked Discord was in a mass outage so I'm not personally in a hurry to get back to archiving since these issues usually reappear for a bit until Discord gets off their asses, lol.

**Comment by chylex** [comment]
Update of the app is released, it includes many changes so I recommend reading the release notes. If nobody finds some critical issue, I will update the browser-only scripts in a few days.
