### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by Imjustarandomlol32** [chylex/Discord-History-Tracker#244]
![Screenshot (8307)](https://github.com/chylex/Discord-History-Tracker/assets/146156012/edb05deb-474a-490b-ad0d-984237bbfe86)
I can't update my old DHT files, what do I do?

**Comment by chylex** [comment]
The database is corrupted, restore it from a backup. Since you haven't provided any steps to reproduce the issue or any details about the database file and how you store it, I can only assume that your disk is faulty.

**Comment by Imjustarandomlol32** [comment]
I've already restored it. All I did was try to update the dht file that was working with v38 and this happened.

**Comment by chylex** [comment]
You can try going back to v38, go to the Advanced tab, and click Vacuum Database before you re-open it in v39.
