### ISSUE TITLE
Getting "Error" when Click "Start Tracking" despite Server status Ready

### ISSUE THREAD

**Issue by TiffanyNeat** [chylex/Discord-History-Tracker#245]
Once again, I am running on Linux (SteamOS). I have upgraded my archive.dht, waited until the internal server says "Ready", and entered the Tracking Script. I get the repeated error `"DevTools failed to load source map: Could not load content for <file path to my discord install, which is a flatpak>/config/discord/0.0.39/modules/discord_desktop_core/core.asar/app/node_modules/@sentry-internal/tracing/cjs/browser/web-vitals/getFID.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"` in the console, and clicking on Start Tracking simple causes results in the Error output w/ no pop-up. This is off the newest update.

**Comment by chylex** [comment]
"DevTools failed to load source map" is not related to anything DHT does. What do you see in the Network tab if you look only at requests to the internal server?

![image](https://github.com/chylex/Discord-History-Tracker/assets/3685160/b22c80c9-8ad8-4171-83b7-309e9875a26e)

**Comment by TiffanyNeat** [comment]
> "DevTools failed to load source map" is not related to anything DHT does. What do you see in the Network tab if you look only at requests to the internal server?
> 
> ![image](https://private-user-images.githubusercontent.com/3685160/292111722-b22c80c9-8ad8-4171-83b7-309e9875a26e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjE5NTAsIm5iZiI6MTcwMzE2MTY1MCwicGF0aCI6Ii8zNjg1MTYwLzI5MjExMTcyMi1iMjJjODBjOS04YWQ4LTQxNzEtODNiNy0zMDllOTg3NWEyNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTIyNzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDM0ZjJkNmRmNDY0NmVlNjQyZDU1NGZhNGUzMDcwZjZjNjc0OTMyZGMyNmE4NWI0NjRlYjFlNGY0OWI2ZTlhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Lo48iRBtaJN-MGKFGInISJLvAr44I2ycl_UpO79wpbM)

![Screenshot_20231221_062711](https://github.com/chylex/Discord-History-Tracker/assets/69395573/e6c8e783-01f3-4373-9bee-b79b1dcad557)
I see this. Also says "POST http://127.0.0.1:50000/track-messages 500 (Internal Server Error)" in the Console when I try again, now.
![Screenshot_20231221_063121](https://github.com/chylex/Discord-History-Tracker/assets/69395573/9a641f16-b749-4f11-9859-b011673732b2)

**Comment by TheTechRobo** [comment]
Try running DHT from a command line and seeing what it outputs?

**Comment by TiffanyNeat** [comment]
> Try running DHT from a command line and seeing what it outputs?

Smart! Once I did this, a click of "Start Tracking" outputs in my terminal the following:
```
[ERROR] [BaseEndpoint] Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table attachments has no column named normalized_url'.
[ERROR] [BaseEndpoint]    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32, sqlite3)
[ERROR] [BaseEndpoint]    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
[ERROR] [BaseEndpoint]    at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
[ERROR] [BaseEndpoint]    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
[ERROR] [BaseEndpoint]    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior)
[ERROR] [BaseEndpoint]    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
[ERROR] [BaseEndpoint]    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
[ERROR] [BaseEndpoint]    at DHT.Server.Database.Sqlite.SqliteDatabaseFile.AddMessages(Message[] messages)
[ERROR] [BaseEndpoint]    at DHT.Server.Endpoints.TrackMessagesEndpoint.Respond(HttpContext ctx)
[ERROR] [BaseEndpoint]    at DHT.Server.Endpoints.BaseEndpoint.Handle(HttpContext ctx, StringValues token)
```

**Comment by chylex** [comment]
Strange, looks like the database didn't get upgraded properly. Can you try opening it in DB Browser for SQLite (or some other db viewer if you already have one), and show the layout of `attachments` and `downloads` tables?

![image](https://github.com/chylex/Discord-History-Tracker/assets/3685160/997d7d2a-ac6f-4046-a456-51c3f9426465)

**Comment by TiffanyNeat** [comment]
> Strange, looks like the database didn't get upgraded properly. Can you try opening it in DB Browser for SQLite (or some other db viewer if you already have one), and show the layout of `attachments` and `downloads` tables?
> 
> ![image](https://github.com/chylex/Discord-History-Tracker/assets/3685160/997d7d2a-ac6f-4046-a456-51c3f9426465)
> 

Oh, damn. That's... definitely because it just didn't. My app hard crashed while it was doing the process, and I was up-until-now under the impression that it finished successfully & just _did that_ for some reason. Thank gods I had a backup of the pre-upgraded version as suggested LOL, I'm re-upgrading with the newest update version, so unless this one goes wrong as well I'll close this Issue once it's done.

**Comment by TiffanyNeat** [comment]
Closing this issue as it is solved, all I had to do was re-upgrade the archive database I was using, which was done successfully on retry. Remember to backup your databases in case this happens to you, as I had to use a backup of mine to re-upgrade it.

**Comment by TheTechRobo** [comment]
Perhaps the app should put a flag into the database while it is updating it, so that it can detect an inconsistent database.
