### ISSUE TITLE
Running the exe froze computer

### ISSUE THREAD

**Issue by goombapatrol** [chylex/Discord-History-Tracker#248]
Just a heads up that DHT might have some sort of memory bug or issue. Happened on latest v40.

I normally grab the **Portable** zip version, but noticed there wasn't a Windows EXE included anymore (any reason?), so i tried self-contained from **win-x64.zip**. Upon running the EXE, my computer became unresponsive (slow mouse no inputs couldn't open task manager etc) and eventually froze completely; had to force hard shutdown after waiting an hour. After it eventually rebooted, i tried the EXE a second time (to rule out it being a different program that caused freeze) and got the same result.

Note that I never saw the actual program window open when this happened; slowdown occurred immediately after running EXE, there are no other steps to replicate.

I'm on Windows 7; coming from DHT Portable **v37.2** which had worked fine (and all versions that i tried before that). Never used the **non-portable EXE** before so that may be relevant.

I confirmed that my old v37.2 build still opens fine without crashing etc (it just isn't compatible with Discord anymore, hence why i needed to update).

I didn't yet test out v39.1 or any in between (so it could be existing bug, not just introduced in v40) because i got some file corruption from the shutdowns, and i don't want to risk any further without consulting first.

Thanks for working on this and let me know if i can provide any other info.

**Comment by chylex** [comment]
DHT 37 runs on .NET 5 which was still supported on Win7, DHT 38+ runs on .NET 8 which requires Win10 1607 or newer.

I can check if I can reproduce the issue on Win7 in a few days out of curiosity, but if it's an issue with .NET 8 then it will not be fixed.

> I normally grab the Portable zip version, but noticed there wasn't a Windows EXE included anymore (any reason?)

The portable version is meant to run via the `dotnet` command, as the instructions on the DHT website say. The exe was a minor convenience, but portable versions only have an exe if you build them on Windows, which I don't anymore. If you have 64-bit Windows, which is the majority of Windows users, there is no reason to use the portable version.

**Comment by goombapatrol** [comment]
> DHT 37 runs on .NET 5 which was still supported on Win7, DHT 38+ runs on .NET 8 which requires Win10 1607 or newer

Thanks for letting me know. (Duly noted about the Portable version.)

https://github.com/dotnet/sdk/issues/27697#issuecomment-1326100360
https://github.com/dotnet/sdk/issues/27697#issuecomment-1352730718

I'm seeing similar experiences elsewhere now that i know what to look for. (They were building in this case, but symptoms match what happened to me enough to think dotnet is probably culprit.)

I wonder if there's a way to do a version check when you run the program for safety? (Better a popup and refusing to run that a total freeze.)
And perhaps there could be a compatibility disclaimer somewhere on your Download page or site.

Lastly, does the browser JS version of DHT still work on all OS, or do i have any options? (Like pasting an updated JS command into console under v37)

And thanks for the quick response.

**Comment by goombapatrol** [comment]
(_oops_ i meant to click "comment" not "close with comment", disregard that) 😄

**Comment by chylex** [comment]
> Lastly, does the browser JS version of DHT still work on all OS, or do i have any options? (Like pasting an updated JS command into console under v37)

Newer versions of DHT serve the tracking script directly from the app, the only thing pasted into the clipboard is a one-line snippet that includes a URL of the full tracking script. If you open that URL, copy the full tracking script to the Win7 computer, and change the server token in DHT to match the tracking script's, it will work with v37 for now.

**Comment by chylex** [comment]
Tested on Windows 7, there is an issue where it uses an excessive amount of memory (over 4 GB), but with enough memory it works. There are available workarounds in https://github.com/dotnet/runtime/issues/79469.
