### ISSUE TITLE
"Go to next channel" functionality stops on group boundaries

### ISSUE THREAD

**Issue by kyanha** [chylex/Discord-History-Tracker#25]
In the setup, I have told DHT to go to the next channel when it reaches the last message.  This option works entirely correctly when the server does not have channel groups.  However, when the server does have channel groups, DHT stops at the end of the last channel in the channel group, even when there are other groups with channels which have not been downloaded.

**Comment by chylex** [comment]
I'm pretty much done trying to make switching to next channel work every time Discord changes something, so the most likely outcome is that eventually it'll stop working for servers completely and I'll maintain it for DMs only. Sorry.

**Comment by chylex** [comment]
I'll fix it in the next update, if it breaks again then idk.
