### ISSUE TITLE
DHT browser version not working

### ISSUE THREAD

**Issue by zamonz** [chylex/Discord-History-Tracker#250]
When I try to track a channel it only tacks 1 message then stops. I've tried all 3 browser methods and it does this for all of them.

**Comment by will-ca** [comment]
Working builds:

https://github.com/will-ca/Discord-History-Tracker/tree/b7a9b6c94ed3ca6a0c207b186031db1e0a1b935b/bld

**Comment by chylex** [comment]
Released update.
