### ISSUE TITLE
Way to visualize files downloaded from chat (archive.dht)

### ISSUE THREAD

**Issue by Mndb1** [chylex/Discord-History-Tracker#252]
Sorry to use the issues page for this. But I was wondering how to access the files downloaded from a Direct Message channel. I have the archive.dht file, but don't know how to visualize its content.

**Comment by chylex** [comment]
Do you mean anything specific with 'visualize', or are you just trying to view the messages?

**Comment by Mndb1** [comment]
The messages I'm able to view just fine, I just can't find a way to view the files that were in that direct message. Am I able to do that?

**Comment by chylex** [comment]
You must use the Downloads tab and download all files within 24 hours of tracking the messages. Discord does not allow viewing files uploaded to their service outside of the Discord app, all links to those files expire after a day.
