### ISSUE TITLE
Links broken in older .txt archives

### ISSUE THREAD

**Issue by ScottQB4** [chylex/Discord-History-Tracker#255]
With the rollout of the new link format and expiries, the links saved won't load when a .txt file is loaded into the viewer.

**Comment by chylex** [comment]
If you're using the browser-only version of DHT, there is no solution. There is an old Python tool that can download links in the archive, but you have to do that before the links expire, and you may end up with duplicate downloads.

The app version of DHT has an option to download attachments automatically, but again, that only works as long as the links haven't expired yet. If the messages still exist, re-tracking them will update the links and the app will download them. It *might* also be possible to paste the expired links back into a Discord channel and tracking that channel, but I haven't tested if that works or what the limits are.

I don't think there's any better solution right now. If pasting links back into Discord and tracking them does work, then it might be the fastest option.
