### ISSUE TITLE
Download messages from a single bot only

### ISSUE THREAD

**Issue by none2004** [chylex/Discord-History-Tracker#257]
Download all messages from the bot that last wrote a message
I use script on Tampermonkey with Firefox

**Comment by chylex** [comment]
The browser-only version of DHT will not be getting new features. The app version has a (manual) way to retain/delete messages made by specific users.

**Comment by none2004** [comment]
I made a mistake. I now have the app version.
Messages from bots via tupperBox, all messages are tracked, but the sender of the messages is only the last bot that wrote. Example :
![exempleMSGBotTupperbox](https://github.com/chylex/Discord-History-Tracker/assets/51090562/42dabf0a-f853-4a6c-8302-ec74b773e492)

give : 
![Result](https://github.com/chylex/Discord-History-Tracker/assets/51090562/a9bc7225-a0b4-434c-a256-36c7681342e8)
