### ISSUE TITLE
[Mac OS] Cannot Open Databases. Can only Create New Ones

### ISSUE THREAD

**Issue by Sylladexter** [chylex/Discord-History-Tracker#258]
Mac OS Monterey: 12.7.4

Whenever I click "Open or Create new Database" I only have the option to save a new database. I cannot open previous ones at all. Clicking on existing databases prompts me to override it. 

Is it possible to make separate buttons for opening and creating?

**Comment by chylex** [comment]
There is no difference between opening and creating a database file. Adding a separate button, that *intends* to overwrite an existing database if you select an existing file, would be new functionality that I'm not sure is wanted.

I specify that an overwrite prompt should not be shown in the GUI library I'm using, but if this option is not supported on Mac OS, then there is nothing I can do about that. The overwrite prompt should only be visual, if it deletes the file on Mac OS then that would be a serious issue, but I haven't had any reports of that.

**Comment by Sylladexter** [comment]
Thanks you for the swift reply! You're right, it _doesn't_ overwrite the file but it does prompt as if it would be overwritten. Really weird, but it's good to know it doesn't actually overwrite anything
