### ISSUE TITLE
Error on threads/channels with Discord's Poll, Discord client restart required to temporary fix it

### ISSUE THREAD

**Issue by Acters** [chylex/Discord-History-Tracker#259]
On a specific discord channel that I keep track of and there is an error that prevents Discord History Tracker from working. Only that specific channel. its really odd to only occur to one channel.

![image](https://github.com/chylex/Discord-History-Tracker/assets/6981852/006c10e4-30ec-4b6d-abd1-2410d53cf874)
![image](https://github.com/chylex/Discord-History-Tracker/assets/6981852/f907eb17-e49e-4f9a-9de7-9b76df1bc85f)
![image](https://github.com/chylex/Discord-History-Tracker/assets/6981852/2631b39c-1b70-4101-971e-50106455b1a9)

The only new thing I could see is that someone started a poll recently. Which I don't believe to be causing the issue, but I am unsure what could be causing the problem.

Restarting the website or Discord App temporarily fixes the issue, but it returns occasionally. Please advise on how to debug this further.

**Comment by chylex** [comment]
You can find the failing request in the Network tab, and copy the message data:

![image](https://github.com/chylex/Discord-History-Tracker/assets/3685160/1782c6eb-6a5c-4c14-afd2-6604292642bb)

Could you send it to me privately, for ex. email it to `contact@chylex.com`? You can redact the text contents of the messages, as the issue appears to be in emoji reactions to messages.

**Comment by chylex** [comment]
I see a problem, currently not sure why it's happening. One of the messages has two reactions, except their count is 0.

Can you find a message in that channel, which was sent at `June 14, 2:45:23 PM UTC`? It should be between two messages that start with "and now..." and "Discord asking..."

According to the data, this message has no text, no attachments, no embeds, but has two broken reactions. If you find a message from that time and it looks like a normal message, then I wonder if it's some kind of temporary blip on Discord's side, and more investigation will be needed.

**Comment by chylex** [comment]
Discord's documentation doesn't explain why poll results are included in the reactions object at all, so I wonder if it's something the web client is doing for itself. It'd probably be best if DHT just ignored reactions with a count of 0.
