### ISSUE TITLE
Formatted embeds are currently not supported

### ISSUE THREAD

**Issue by Escaflownevan** [chylex/Discord-History-Tracker#26]
Could you say how long this be will?

**Comment by chylex** [comment]
Probably until someone else makes a PR for it.

**Comment by binsenpai** [comment]
So you can't? @chylex 
FeelsUnskilledMan
joke

**Comment by xFirez** [comment]
Anyone able todo this?

**Comment by chylex** [comment]
That's already implemented, formatted embeds are way more complicated.

**Comment by chylex** [comment]
Closing the issue, if someone wants to make a PR for this they can.
