### ISSUE TITLE
DHT Viewer Error

### ISSUE THREAD

**Issue by Acters** [chylex/Discord-History-Tracker#260]
So recently, I noticed that you updated the viewer. I tried opening it and received the following error:
![image](https://github.com/chylex/Discord-History-Tracker/assets/6981852/1394b84a-8087-4ed4-9ef6-dfd7f712e63a)
![image](https://github.com/chylex/Discord-History-Tracker/assets/6981852/c6ab998c-f0f9-41c1-aa5d-e83b7ce37514)

**Comment by chylex** [comment]
Which browser and browser version are you using?

**Comment by chylex** [comment]
The change that caused this has broken compatibility with Safari, I don't know if it's the only thing that doesn't work in Safari but I will look into it.
