### ISSUE TITLE
Unable to migrate older database (V42.1) to (V43)

### ISSUE THREAD

**Issue by cvyl** [chylex/Discord-History-Tracker#264]
During migration, it threw a foreign key error.
![image](https://github.com/user-attachments/assets/e1d5aa96-8c76-4d4f-81fb-996c86041ae3)
After that it says the following:
![image](https://github.com/user-attachments/assets/2b169690-07af-4a58-bc45-5b896cdf305a)
Deleting the existing table repeat the first screenshot. I am unable to migrate my database.

**Comment by chylex** [comment]
Can you please run DHT with `-console -debug` arguments? For example, by creating a shortcut to the exe and adding that to the Target.

![obrazek](https://github.com/user-attachments/assets/d8dbeda8-9506-474a-86d7-ce95cf5a4a2a)

Then when you try the migration again, take a screenshot of the error in the console window.

**Comment by cvyl** [comment]
https://pastebin.com/tHA6nRqh
![image](https://github.com/user-attachments/assets/42d8ff4d-8a85-4f03-882a-040eed34fe59)

**Comment by cvyl** [comment]
As far as I know, it did make the message_attachment table (looking in with sqlitebrowser) but for the rest it seems to have failed completely.
![image](https://github.com/user-attachments/assets/5810168b-c822-4ae9-8643-2dac2f052a61)
after
![image](https://github.com/user-attachments/assets/61833a11-5518-447a-9e2d-ccb2568c6361)

**Comment by chylex** [comment]
I'm guessing the problem is that some messages have been deleted, and there are leftover attachments associated those messages. I don't know if this could have happened due to a bug in the Viewer tab's functionality to delete messages based on filters, or if you edited the file externally?

**Comment by cvyl** [comment]
> I'm guessing the problem is that some messages have been deleted, and there are leftover attachments associated with those messages. I don't know if this could have happened due to a bug in the Viewer tab's functionality to delete messages based on filters, or if you edited the file externally?

I haven't modified the file externally but have deleted message entries from bots a few months back.

**Comment by chylex** [comment]
Restore a backup or delete the table again, and try v43.1.

**Comment by cvyl** [comment]
> Restore a backup or delete the table again, and try v43.1.

This seems to have fixed it. Thank you very much!! I've been using this software for years and appreciate the swift support!
