### ISSUE TITLE
Adding support for other databases

### ISSUE THREAD

**Issue by Kingistel** [chylex/Discord-History-Tracker#271]
Kind of duplicating #199  in a way.

> Option to pick what kind of database type to use (JSON, MySQL, etc)

I would like to be able to use, for example. MySQL server.

Externally realize as buttons “Open local base” which will use SQLite and “Open external base” which will open a window with the input of host, login-password and name of the base to connect to MySQL.

**Comment by chylex** [comment]
No plans to support other databases.
