### ISSUE TITLE
Messages from "likely spammers" are ignored

### ISSUE THREAD

**Issue by smowtenshi** [chylex/Discord-History-Tracker#272]
My friend's account was flagged by Discord as "likely spammer" so his messages are hidden (similarly to blocked messages) and it seems that DHT is ignoring them.
![image](https://github.com/user-attachments/assets/572efd08-d745-46dd-834e-ad854d72d5f2)

I can't see anything in the console related to that - the only thing that gives it away is a value `1048576` in `messages[n][n].author.public_flags` API request and quick internet search seems to confirm that.

**Comment by chylex** [comment]
Coincidentally I rewrote the tracking mechanism a few months ago but haven't released it yet, and it turns out the new method can see hidden messages. Closing as resolved by 0229c00259ef989c73814a95c1954a589665bad7.
