### ISSUE TITLE
Detecting deleted messages

### ISSUE THREAD

**Issue by Lynxy** [chylex/Discord-History-Tracker#28]
Redacted

**Comment by chylex** [comment]
Finding deleted messages is not the intention of DHT, as it would require re-scanning messages that are already stored.

**Comment by Lynxy** [comment]
That was actually the reason that brought me to DHT. Deleted messages are more valuable to me than regular messages, so I modified the scripts to support it. It is a very hackish job but works for what I need.

If you are curious as to what I did it is rather simple. The tracker stores a "last seen" timestamp on all messages. The viewer then compares the last seen time with the next sequential message, and if the time differs too much it is flagged as deleted. Not foolproof, I know, but seems to work well enough. Does not require a complete scan to detect recently deleted messages either.

**Comment by chylex** [comment]
It can reasonably be used if you have it running all the time without autoscroll and I thought about such use case, but I don't want to add anything specific to it.
