### ISSUE TITLE
Not capturing the top 4 messages in DMs

### ISSUE THREAD

**Issue by ShadowRain-** [chylex/Discord-History-Tracker#29]
For some reason on DMs it will stop before capturing the top 4 messages. If a DM with a person only has 4 messages (or less) it will skip it entirely.

(Thank you for all your work on this! It's been so helpful.)

**Comment by chylex** [comment]
Weird. It looks like it finds the messages if you start tracking, switch to a different user, and then switch back. I'll figure out what's going on when I have time.

**Comment by ShadowRain-** [comment]
Yeah, sometimes if I do things in exactly the right way it'll find the messages, but not always. Unfortunately, I wasn't able to find a way that always worked. 
Thank you for looking into it

**Comment by chylex** [comment]
The next update should work better, I still found a case where one message wasn't captured on a server as opposed to DMs, not sure why.

**Comment by ShadowRain-** [comment]
That would be awesome! I never could find much of a pattern over the last several months--sometimes it would capture everything, even if there were only three messages in a DM, other times it would skip the whole thing even if there were like twenty messages, and I did run across the one you mentioned too where it'd capture the whole thing except for the first message on the server. It's been strange lol. This tool is so useful though, it'll be such a relief to have it working again. :)

**Comment by chylex** [comment]
I found some DMs where it always skipped a few messages or completely ignored them, this update fixed those. Then I found a few more cases that still caused issues, so idk.

**Comment by chylex** [comment]
Is this still an issue with the latest versions or either the app or browser-only version of DHT?

**Comment by ShadowRain-** [comment]
I tested it with the most recent versions of both the app and the browser-only version and it had none of the problems with catching all the messages that I used to get, so this one seems to be solved. Thank you again for all your work!
