### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by chylex** [chylex/Discord-History-Tracker#3]
Global + per-channel statistics.

- [ ] UI
  - [ ] Toggle button that switches between message & statistics view
  - [ ] 'Global Statistics' section in channel list
- [ ] Calculations
  - [ ] Total messages (overall and per user)
  - [ ] Total characters (overall and per user)

**Comment by guwniak** [comment]
It would be great, if you implemented this. I think you can also make statistics by month, i.e how many posts wrote user in december, or all posts in december.

**Comment by Encarton** [comment]
The message count from the script and the message count from using Discord's search don't match up.
Not sure if it is a bug, or if it drops a few messages here and there

**Comment by chylex** [comment]
I have decided to not add detailed statistics directly into the viewer and complicating things; with the app version of DHT, the archives can be analyzed using SQL which is way more powerful than any overview I could come up with.
