### ISSUE TITLE
Uncaught Syntaxerror

### ISSUE THREAD

**Issue by Lyrina25** [chylex/Discord-History-Tracker#30]
After copying the code and pasting it into the right area, I get this instead. I'm not exactly sure what I should post here to help fix this error..

https://i.gyazo.com/89c73cf290dc915d2a1be51cf1a90488.png

**Comment by chylex** [comment]
Which browser did you use to copy the code?

**Comment by Lyrina25** [comment]
Google chrome

**Comment by chylex** [comment]
Both `Copy to Clipboard` and copying link to `tracker script` work fine in Chrome 64, so I can't reproduce the issue. Try disabling extensions and clipboard managers if you have any. If nothing works, paste the script into https://gist.github.com and send a link so I can take a look.

**Comment by Lyrina25** [comment]
Alright, well disabling all my extensions didn't work, so here's the code I'm getting when i click 'copy to clipboard' and copy the code.


javascript:(function(){var e=function(){var n=function(){let e=t.s("messages");return e&&e.children.length&&e.children[0]},s=0,i=0;return{i:function(e){var a=function(){let s=n();if(s)if(s.classList.contains("loading-more"))r(25);else{let n=t.s("messages").children.length;n<100&&(i=0),i>0?(--i,r(750)):(n>300&&(i=6,t.o(()=>{let e=t.s("messages");e.scrollTop=e.scrollHeight/2},1)),e(s.classList.contains("has-more")),r(200))}else r(500)},r=function(e){s=t.o(a,e)};a(),window.l.push(()=>window.clearInterval(s))},h:function(e){var t=Object.keys(e||{}).find(e=>e.startsWith("__reactInternalInstance"));return t?e[t].memoizedProps:null},g:function(){try{var n,s,i=t.s("private-channels");if(i){if(!(s=t.s("selected",i)).classList.contains("private"))return null;var a=t.p("a",s).href.split("/"),r=[].find.call(t.s("channel-name",s).childNodes,e=>e.nodeType===Node.TEXT_NODE).nodeValue;if(!r)return null;n={server:r,channel:r,id:a[a.length-1],type:t.v("status",s).length?"DM":"GROUP"}}else{s=(i=document...{return this.G()._e(e)},i.prototype.Z=function(t){e.push(t)},new i}();if(!window.location.href.includes("discordapp.com/")&&!confirm("Could not detect Discord in the URL, do you want to run the script anyway?"))return;if(window.DHT_LOADED)return void alert("Discord History Tracker is already loaded.");window.DHT_LOADED=!0,window.l=[];let l=!1,c=function(e){l=!0,t.o(()=>{o.ae();l=!1;e&&e()},200)};e.i(t=>{if(o.R()&&!l){let n=e.g();if(!n)return void c();o.Ee(n.server,n.type,n.id,n.channel);let s=e.T();if(!s.length)return void e.A();let a=o.Re(n.id,s);if(r.autoscroll){let n=i.he;a||o._e(s[0].id)?t||(n=r.afterFirstMsg):n=r.afterSavedMsg,n===i.pe&&!e.C()||n===i.ge?o.ae():e.A()}}}),o.Z((t,n)=>{if("tracking"===t&&n){let t=e.g();if(!t)return void c(()=>alert("The selected channel is not visible in the channel list."));if(o.Ee(t.server,t.type,t.id,t.channel),o.Re(t.id,e.T()),r.autoscroll&&e.S())if(e.O())e.A();else{let t=r.afterFirstMsg;(t===i.pe&&!e.C()||t===i.ge)&&c()}}}),n.Y(),a&&n.ie();})()

**Comment by chylex** [comment]
I wanted gist because the code is like 13 thousand characters, not 20 lines. Your browser is copying it wrong, idk why.

**Comment by Lyrina25** [comment]
Is there anywhere else to get the code?

**Comment by chylex** [comment]
Try saving it as a bookmark or use a different browser.
