### ISSUE TITLE
Can't download after 500k+ messages have been saved

### ISSUE THREAD

**Issue by bluefiberbread** [chylex/Discord-History-Tracker#32]
I'm unable to download after that many messages have been saved. I'm using the latest version of Chromium with 32GB of RAM

**Comment by chylex** [comment]
Try Firefox or don't save that many messages into a single file. Chrome/Chromium can't handle it.

**Comment by excinera** [comment]
Using the desktop version of Discord (v0.0.8 on Debian), I've archived servers with far more messages and far less RAM -- there is, however, a very long delay between clicking the "download" button and getting a save-file dialog. This looks a lot like the program's hung (we're talking multiple minutes), but it eventually pulls through. I recommend clicking it right before you take a bathroom break or go make a cup of coffee!
