### ISSUE TITLE
iFrame API?

### ISSUE THREAD

**Issue by thehappydinoa** [chylex/Discord-History-Tracker#35]
Could you maybe implement an iFrame that accepts a server and channel id and gives you an iframe widget?

**Comment by chylex** [comment]
Browsers don't allow injecting scripts into cross-domain iframes, so it's not possible afaik.

**Comment by thehappydinoa** [comment]
@chylex what if you make a server that hosts a copy?

**Comment by chylex** [comment]
That doesn't matter, it still has to run in your browser and browsers won't allow it. It would be possible if DHT was an addon or userscript, but not as a bookmark script.

**Comment by thehappydinoa** [comment]
Ah ok
