### ISSUE TITLE
List of users

### ISSUE THREAD

**Issue by rumplepusscat** [chylex/Discord-History-Tracker#38]
It would be a nice addition if a live "snapshot" of all the users in the Discord server could be taken, perhaps including their profile images. Some users don't speak and it would be useful to see who was in the server at the time, and perhaps their status/rich presence/offline or not.

Thanks

**Comment by chylex** [comment]
There's a few reasons this probably won't happen, sorry.

- I think the user list works similarly to the channel list, where it doesn't actually load all users so getting the full list is a PITA
- The only viewer feature that uses a user list is the user filter which shouldn't have silent users, not planning to add any specific user list UI right now

DHT only works with Discord UI, there might be other tools or bots that work with the API, which would be better for this purpose.

**Comment by rumplepusscat** [comment]
OK, valid reasons.
