### ISSUE TITLE
Help: Different kind of export

### ISSUE THREAD

**Issue by Milotrince** [chylex/Discord-History-Tracker#39]
Hi!
I was using dht to extract chatlogs from discord to put the data into a spreadsheet to do things like this:  https://docs.google.com/spreadsheets/d/11vFkOFpvcmVBWtKcYvgRYjYGKNW39lmvjCeVoe6RYk8/edit?usp=sharing

I've been using a simple script to format the JSON file dht gives into this format (separated by tabs):

```
6/14/2018   1:23:45 PM   0   wooow
6/14/2018   1:23:47 PM   0   this is neat-o
6/14/2018   1:23:50 PM   1   yes
6/14/2018   1:23:55 PM   1   indeed it is
```
[formatter.txt](https://github.com/chylex/Discord-History-Tracker/files/2109565/formatter.txt) (change to .js)

I've been trying to figure out the tracker script, but it's a bit difficult to read, the least I could do was change around colors to look a little nicer like this:
![screen shot 2018-06-18 at 10 41 13 pm](https://user-images.githubusercontent.com/19580648/41578789-ca7a43ae-7348-11e8-843f-73fc72e8eef4.png)
(color modified tracker script https://hastebin.com/raw/rucijaluwi)

Soo I am not super experienced, but I'd like to figure out a way to add a button to the paste-able tracker that could export it this way in one step...  I think I could try figuring it out if I had a non-simplified version of the original script, but I don't know where to find that.  If anyone could help me, thanks!

**Comment by chylex** [comment]
**GUI buttons and click listeners:**  
https://github.com/chylex/Discord-History-Tracker/blob/master/src/tracker/gui.js#L102-L142

**Download button callback:**  
https://github.com/chylex/Discord-History-Tracker/blob/master/src/tracker/state.js#L80-L84

**Archive file format:**  
https://github.com/chylex/Discord-History-Tracker/blob/master/src/tracker/savefile.js  
(specification on top which is actually missing some newer stuff like rich embeds but it shouldn't be a big problem, code & json conversion below that)
