### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by magnapeccatrix** [chylex/Discord-History-Tracker#42]
I don't know if discord had an update to block this script but when I click on bookmark nothing happens.

If I click on bookmark outside of discord app website, it tells discord not found in URL.

**Comment by chylex** [comment]
Not happening to me, I guess your bookmark has an old version of DHT. If it still doesn't work after updating the bookmark, re-open the issue and post any errors you see in the browser console.

**Comment by magnapeccatrix** [comment]
Hello, Chylex

I have bookmarked the current script for firefox and when I click on it while I am on discord inside Firefox, nothing happens.

When I click it on any other site, it says could't detect Discord in the Url.

I don't know how to diagnose this. It was working recently.

**Comment by chylex** [comment]
If you open `google.com`, run the bookmark, click OK on the prompt, and open Settings. It should say `BETA v.8, released 5 Aug 2018` on the bottom - if it doesn't, then remove the bookmark and get a new one from https://dht.chylex.com/

**Comment by chylex** [comment]
Ah, it looks like Discord has started blocking bookmarks. Unfortunately there's not much I can do about that. I'll have to update the website, but I don't have much time right now.

You can still use DHT in Firefox - there is a `How to save history -> ...using the Discord app` section on the DHT website, you can follow the same steps in Firefox.

**Comment by chylex** [comment]
Updated the website with new instructions.
