### ISSUE TITLE
Suggestion: Page Select

### ISSUE THREAD

**Issue by AgentRAF** [chylex/Discord-History-Tracker#43]
I've been using DHT for some of my other projects.  It's been working well so far, but I have not so much as an issue, but a suggestion.  When the documents get long (like 153 pages in a file), I find it annoying when you need to scroll to the middle and need to click a button 50-something times to reach the desired page.  Can you guys add a function where you can specify what page you want to go to?  Or is that already present, and I just don't know how to access it?  Thanks!

**Comment by chylex** [comment]
There currently isn't one. It's a good idea, but I would not recommend having this many pages in one file; when the archive reaches a certain size, browsers will not be able to process it anymore.

**Comment by AgentRAF** [comment]
Just a note:  I'm using 50 texts per page, and DHT registers all 153 pages just fine using the one file.

**Comment by chylex** [comment]
That's actually fine. I'll add some way to navigate pages easier, in the meantime you can use the browser console, for example this skips 10 pages:
```
for(let a = 0; a < 10; a++) document.getElementById("nav-next").click()
```
