### ISSUE TITLE
Multiple Sort

### ISSUE THREAD

**Issue by T0xicFury** [chylex/Discord-History-Tracker#44]
You should add the ability to add multiple filters, such as searching for specific message contents by specific people.

**Comment by chylex** [comment]
Good idea, but it would need quite a few changes I don't have time to do myself. If you or someone else wants to implement this and send a PR, post a comment into this thread and I'll quickly summarize what would need to be changed.

**Comment by chylex** [comment]
The app version of DHT has several filters such as a multi-selection of channels and users, and you can combine that with filters inside the viewer. The new archive format can also be processed using SQL, which is more complicated, but it's a very powerful tool.
