### ISSUE TITLE
The selected channel is not visible in the channel list.

### ISSUE THREAD

**Issue by ShadowRain-** [chylex/Discord-History-Tracker#45]
When trying to track DMs, it comes up with a popup that says "The selected channel is not visible in the channel list." Tracking channels on servers works just fine still, but no DMs will work. It wasn't doing that on Tuesday so it might have been one of the recent discord updates that caused it.

(thank you for your time, I love this tool!)

**Comment by chylex** [comment]
Yea, I knew an update would break it eventually, I'll fix it in a few days.
