### ISSUE TITLE
I love this app!!!! 

### ISSUE THREAD

**Issue by infominer33** [chylex/Discord-History-Tracker#47]
I just wish it would grab the links for files dropped directly into discord, rather than skipping or just leaving the text name of the file.

**Comment by simdimdim** [comment]
I concur with the title.

**Comment by infominer33** [comment]
I see you've been working on the images and files so now I can click a button to download. Is there any way to get a text link additionally? That way I can copy paste the whole channel with all the links. :D  Thank You!

**Comment by chylex** [comment]
Feel free to reopen and comment if there are any unanswered questions, I'm closing the issue due to inactivity.
