### ISSUE TITLE
Output Issue

### ISSUE THREAD

**Issue by GamingFlame** [chylex/Discord-History-Tracker#49]
Is it supposed to end up like this because I've tried multiple different things and it always comes out like this. If it is how it's supposed to turn out then how can i make it like way more simple xd. Also I am downloading direct messages
![desktop screenshot 2018 11 24 - 02 36 40 03](https://user-images.githubusercontent.com/33568546/48967207-d05f4100-ef91-11e8-8187-6dbd12a3c34f.png)

**Comment by chylex** [comment]
If you want to view the messages, use the [viewer](https://dht.chylex.com/build/viewer.html). If you want to analyze them or convert them to another format, see the [format specification](https://github.com/chylex/Discord-History-Tracker/blob/master/src/tracker/savefile.js).
