### ISSUE TITLE
Chrome - Network error when downloading

### ISSUE THREAD

**Issue by chylex** [chylex/Discord-History-Tracker#5]
Use createObjectURL to bypass the error.

**Comment by jahands** [comment]
Running into this issue if I try to load/download too many chats in a single file.

**Comment by chylex** [comment]
I'll work on that soon, and iron out some other issues.

**Comment by jahands** [comment]
Thank you so much! Have a beer on me =)

**Comment by chylex** [comment]
Closed by https://github.com/chylex/Discord-History-Tracker/pull/8
