### ISSUE TITLE
The possibility of a downloadable viewer program

### ISSUE THREAD

**Issue by Divine-Knight** [chylex/Discord-History-Tracker#50]
Out of curiosity, what would be the possibility of the viewer for the history tracker becoming a program on its own that can be downloaded and used without a browser? I'm asking because I much prefer loading a text file of Discord history on a downloaded program rather than on a web browser.

**Comment by chylex** [comment]
If you don't want to open the archive in your own browser then download a portable browser. I could make it into a downloadable program, but it'd literally just be a downloadable web browser with the viewer in it, there's no point.
