### ISSUE TITLE
A possible desktop application version?

### ISSUE THREAD

**Issue by TinyGhostOtus** [chylex/Discord-History-Tracker#51]
I was wondering, if it was possible, if you would create a version of this for those who use the Discord desktop app at some point. The program you've created is great however I - along with others - tend to not use the web browser version of Discord much but we do use the desktop application (mostly due to the fact that it is far more easy to use the desktop app than web browser for us) instead which means that I can not use it as much as I hoped.

**Comment by chylex** [comment]
The instructions say how to use the script in the Discord app.
