### ISSUE TITLE
The selected channel is not visible in the channel list.

### ISSUE THREAD

**Issue by whalehub** [chylex/Discord-History-Tracker#53]
I'm receiving this error when trying to track the Discord DMs of one person in particular. Virtually every other person is working fine. I was previously able to track the DMs with that person, but it stopped working sometime in the past couple of months.

Could you have a look at what's causing the issue? Let me know if you need more information from me to troubleshoot it.

**Comment by whalehub** [comment]
The issue resolved itself at some point during the past few days.

**Comment by chylex** [comment]
Resolved in #58
