### ISSUE TITLE
Broken by new Discord update

### ISSUE THREAD

**Issue by excinera** [chylex/Discord-History-Tracker#56]
While working on my fork of the code, Discord auto-updated and I found that in the new version my tracker didn't scrape any messages.

So I built the pastable script from the stable DHT version and that didn't work either.

It seems to be displaying 0 messages saved, no matter how many are scraped through.
![image](https://user-images.githubusercontent.com/25412314/52156774-51088080-2658-11e9-8e32-1cce01573d2a.png)

And this is what the file output looks like -- it's grabbing the server information and channel information, but failing to collect messages somehow. 
![image](https://user-images.githubusercontent.com/25412314/52156840-aa70af80-2658-11e9-92c5-8ad6b5358ecd.png)

**Comment by excinera** [comment]
I can confirm that it's also broken on the web version.

**Comment by chylex** [comment]
Something probably changed in the DOM structure, I'll take a look tomorrow.

**Comment by excinera** [comment]
Okay, I figured out a fix. I'm testing it right now to make sure it works, and I'll submit a pull request tomorrow.

**Comment by Error-Forbidden** [comment]
> 
> 
> Okay, I figured out a fix. I'm testing it right now to make sure it works in all circumstances, and I'll submit a pull request tomorrow.

Were you able to find a solution?

**Comment by chylex** [comment]
I'll get to it today, forgot it's been 4 days already.

**Comment by Error-Forbidden** [comment]
> 
> 
> I'll get to it today, forgot it's been 4 days already.

The JavaScript on your website still does not work. What do I need to do?

![bilde](https://user-images.githubusercontent.com/23483786/52297062-2bdd8000-2980-11e9-87bb-e14968b4478e.png)

**Comment by chylex** [comment]
Wait for the update.
