### ISSUE TITLE
Tracking is not working properly, it won't Pause Tracking or Switch to Next Channel after reaching a previously saved message...

### ISSUE THREAD

**Issue by COLDsteem** [chylex/Discord-History-Tracker#57]
It seems broken after recent updates... as the title says, Tracking won't Pause or Switch to Next Channel after reaching a previously saved message...

I've Uploaded the latest file from my backup, started tracking, but the Tracker just kept going even after reaching a previously saved message.

The same thing happened with a previous backup file I had.

**Comment by chylex** [comment]
Already commented on the previous issue. I'll delete this one once you've had a chance to see it.
