### ISSUE TITLE
Tracking fails on group chats

### ISSUE THREAD

**Issue by Pneumaticat** [chylex/Discord-History-Tracker#59]
It works fine on DMs and servers, but not group chats. I've tried on every group chat I have, and it gives the error "The selected channel is not visible in the channel list." I tried on Firefox and the official discord app.

**Comment by chylex** [comment]
Confirmed, a recent update must have changed something again.

**Comment by chylex** [comment]
Confirmed, a recent Discord update must have changed something again.

**Comment by Error-Forbidden** [comment]
> 
> 
> Confirmed, a recent Discord update must have changed something again.

Have you found a solution yet?

**Comment by chylex** [comment]
Not working on the project at the moment, I could take a look during the next week.

**Comment by Error-Forbidden** [comment]
> 
> 
> Not working on the project at the moment, I could take a look during the next week.

😅

**Comment by Error-Forbidden** [comment]
Any news on this?

**Comment by Pneumaticat** [comment]
@chylex thank you so much!

**Comment by AJolly** [comment]
Seems to be giving the same issue again.
