### ISSUE TITLE
Make DHT work inside Discord app & add persistence

### ISSUE THREAD

**Issue by chylex** [chylex/Discord-History-Tracker#6]
- [x] Make sure the script works in Discord's dev tools
- [x] Store last script settings in local storage for both Discord and browsers
- [x] Add a way to exit the script UI and delete the script from memory when done

**Comment by ShadowRain-** [comment]
Does this mean that there's some way that DHT can be run locally inside of the discord app now? That would be amazing if so...

**Comment by chylex** [comment]
It is possible, but not with the bookmark. I'll update the website with a guide soon.

**Comment by chylex** [comment]
Website updated.

**Comment by ShadowRain-** [comment]
Thank you so much!
