### ISSUE TITLE
Read emoji reactions.

### ISSUE THREAD

**Issue by AnastasiaDunbar** [chylex/Discord-History-Tracker#60]
It would provide more context to messages if they were included.
`span[class^="reactions-"]` → (`div[class^="reaction-"]` → (`img[class="emoji"]`→`.alt`, `div[class^="reactionCount-"]`→`.innerText`)).
Also not to forget that there are custom emojis.

**Comment by chylex** [comment]
DHT doesn't even work with custom emoji, basically any feature Discord added after 2016 isn't supported very well.

**Comment by chylex** [comment]
Issue resolved thanks to #135.
