### ISSUE TITLE
I don't seem to have a DHT button

### ISSUE THREAD

**Issue by AugustusDraconus** [chylex/Discord-History-Tracker#61]
I installed with ViolentMonkey on Firefox 65.0.2 on Windows 7.  I installed the Userscript and opened the Discord browser app. I have noted that DHT for the desktop app appears to work fine at the moment. Thanks for your work. Cheers.
![No_DHT_Button](https://user-images.githubusercontent.com/5923374/54494168-e03ac200-48ad-11e9-83a0-45c21740eb29.PNG)

**Comment by robertpateii** [comment]
Hello, this was Duplicated by #71 which has more discussion on it. follow it if you’re interested.

**Comment by chylex** [comment]
Please read https://github.com/chylex/Discord-History-Tracker/issues/71#issuecomment-528612086.
