### ISSUE TITLE
New discord interface?

### ISSUE THREAD

**Issue by thibaultmol** [chylex/Discord-History-Tracker#65]
Seems like script is broken because of an update to Discord's ui today.

**Comment by shawneric** [comment]
Confirmed.

**Comment by AnastasiaDunbar** [comment]
If this will be fixed and that it'll happen again in the future, wouldn't it be better to implement separately the way how it'd read their HTML elements if possible?

**Comment by AnastasiaDunbar** [comment]
I don't really remember about the old version:
**Old**: `messagesWrapper` → ... → ( `headerCozy` | `headerCompact` ) → ?.
**New**: `messagesWrapper` → ... → ( `containerCozyBounded containerCozy container` → `contentCozy` → `containerCozy container` → `markup` | `containerCompactBounded containerCompact container` → `messageCompact` → `contentCompact content containerCompact` → `markup` ).

**Comment by thibaultmol** [comment]
@AnastasiaDunbar can you modify the project to make it work again and pull request it?

**Comment by shawneric** [comment]
This still isn't working :(

**Comment by chylex** [comment]
> If this will be fixed and that it'll happen again in the future, wouldn't it be better to implement separately the way how it'd read their HTML elements if possible?

All HTML/React stuff is in `tracker/discord.js`. The question is which elements now contain the internal React data, and whether the structure of that data has changed (unlikely, but I haven't had the time to look at it yet).

**Comment by chylex** [comment]
The new UI changed some things that made it a lot more difficult to detect channels for auto-switching, right now I made it detect the channel icon which will break if they change it, or in special cases like if a text channel has a *lock* on top of it or whatever other variations there may be...

If someone finds a better way to detect text channels apart from voice channels, I'd appreciate a PR or an idea in comments, under the condition that the code *must prove a channel is a text channel*, i.e. it cannot detect voice channels and assume that any non-voice channel is a text channel.
