### ISSUE TITLE
Viewer: export to HTML files

### ISSUE THREAD

**Issue by phoe** [chylex/Discord-History-Tracker#67]
Is there a way for the Viewer to export the archive as a set of static HTML files (possibly with some JS to navigate between pages)?

I am looking for a way to archive a Discord server and plant the archive as a set of HTML files that are viewable without the use of an external application.

**Comment by chylex** [comment]
There isn't, a possible solution would be to embed the archive file into the viewer html, and load it when the page is opened.

**Comment by phoe** [comment]
I imagine the following: if the viewer generates a HTML tree to display the rendered channel in the browser, would it be much of an effort to dump that tree to a HTML file? A loop over all channels in a server would then do all that I want.

**Comment by chylex** [comment]
I have no plans to do either right now, embedding the archive would be the easiest way since the viewer already has formatting and pagination, otherwise you'd have to do that yourself.

**Comment by chylex** [comment]
Further updates in #20.
