### ISSUE TITLE
Doesn't work in safari

### ISSUE THREAD

**Issue by eduarcor** [chylex/Discord-History-Tracker#70]
In the last safari with last Mojave doesn't appear the DHT menu... (in chrome works)

**Comment by chylex** [comment]
Looks like [Safari no longer works with Tampermonkey](https://github.com/Tampermonkey/tampermonkey/issues/558#issuecomment-484370453), so unless you can find a different userscript manager extension for latest Safari, you'll have to use a different browser.

**Comment by chylex** [comment]
Someone in that thread recommended https://github.com/quoid/userscripts, might be worth a try. Closing the issue though, since it's not specifically a problem with DHT.
