### ISSUE TITLE
I don't have a DHT button

### ISSUE THREAD

**Issue by dkjfklsdj** [chylex/Discord-History-Tracker#71]
I'm using Windows 8.1 64 bit on Firefox with Violentmonkey. I have no DHT button in the desktop app or the website, but the tracker script shows up in the add on menu and it's toggled on. Help? 
![bdce08f0a2aca703b6199641e2a876cc](https://user-images.githubusercontent.com/52597673/60754726-009ca280-9fab-11e9-9cd6-182ef6da1a5d.png)

**Comment by robertpateii** [comment]
I had the same problem. If you're script savvy, you can just add ```// @inject-into auto``` into the settings at the top of DHT.

If you aren't, go to ViolentMonkey settings and change "default injection mode" to "auto" like so:

![image](https://user-images.githubusercontent.com/494069/61990252-8d62db00-b002-11e9-921e-cfbc9abd9982.png)

Detailed explanation on the ViolentMonkey blog:



> By default, a script will try to execute in the page context. In Firefox, this may fail in CSP restricted pages.

> You can change the default behavior in the settings tab of Violentmonkey. By changing the default injection mode to auto, scripts that do not depend on traditional unsafeWindow will work again in Firefox.
> Published at 23 Nov 2018
https://violentmonkey.github.io/2018/11/23/inject-into-context/

**Comment by robertpateii** [comment]
Bad news: if you fix this then it still doesn't work because you it can't find the channels. I think it's related to #69 and discord having changed their CSS class names. I assume this breaks it in every browser.

**Comment by chylex** [comment]
The script requires access to javascript objects, that doesn't work in violentmonkey's *content* mode (or *auto* with CSP). There is no fix, violentmonkey **must** bypass CSP to stop websites from blocking userscripts.

**Comment by robertpateii** [comment]
I see. 

> The content context is an isolated world, scripts in this context have no access to JavaScript objects from page context. But they can communicate with DOM APIs such as addEventListener.

This is why content mode will add the DHT button but the script still fails because it needs the objects on the page from discord’s servers. 

So should I make a pull request to the web and docs that say violentmonkey + Firefox is not supported? Then you could close the related issues.

**Comment by chylex** [comment]
I'll have to see what combinations work nowadays, and whether Chrome's planned extension API changes would break the ability to modify CSP, which would basically break DHT as a userscript everywhere.

**Comment by chylex** [comment]
I have tested the following combinations:

| Browser | Addon | Status |
|---------|-------|---------|
| Firefox | GM | Broken, has DHT button |
| Firefox | VM | Broken, no DHT button |
| Firefox | TM | Working |
| Chrome | VM | Working |
| Chrome | TM | Working |

From discussions on TM issue tracker, Safari no longer works. I just fixed a bug in Edge, wasn't able to install TM there because Microsoft Store is just broken... but it *should* work there.

I'll update the userscript manager recommendation on the website accordingly.

**Comment by ssokolow** [comment]
Any chance you could report this as a big to the Greasemonkey and Violentmonkey devs and tell me the bug ID so I can subscribe?

I stopped considering Tampermonkey to be an acceptable option as a result of this:

> This repository contains the source of the Tampermonkey extension up to version 2.9. All newer versions are distributed under a proprietary license.

**Comment by chylex** [comment]
You're free to report the issue to them. The initial cause (CSP) has been reported to VM before, their solution was what was discussed earlier which doesn't work for DHT. I don't know what the exact problem with GM is, but it appears to work with GM 3 and not GM 4.

**Comment by ssokolow** [comment]
I wouldn't feel comfortable being the point of contact when my understanding of the problem is so superficial.
