### ISSUE TITLE
Feature suggestion: Text fields, deleted messages

### ISSUE THREAD

**Issue by UnforeseenOcean** [chylex/Discord-History-Tracker#74]
1. Push the message field up so I can see what I type
2. Add an option to not remove deleted messages from the history or remove that functionality altogether

**Comment by chylex** [comment]
DHT is made to keep deleted messages. The only possibility I can think of off the top of my head is that Discord started serving empty messages with the IDs of deleted ones so they get overwritten, but I'll have to investigate.

**Comment by chylex** [comment]
Can't reproduce the issue with DHT removing deleted messages.
