### ISSUE TITLE
Has anyone actually faced repercussions for using a tool like this?

### ISSUE THREAD

**Issue by generic-github-user** [chylex/Discord-History-Tracker#76]
[Archive Team](https://www.archiveteam.org/index.php?title=Discord) recommends this tool (which is incredible) but warns that this and similar tools are against the Terms of Service. It seems generally known that Discord does not take actions against users for minor TOS violations and I think that the use of a data extraction tool is justified the absence of such a tool built into Discord (especially since there is _no_ support for preserving direct messages or group messages). Discord allows users to export their own messages but these are often useless without context, and this can take weeks; it is natural for users to want to protect the data they have accumulated over time.

Furthermore, there are large servers directly on Discord for users of tools like BetterDiscord, which also contradict the TOS, and I have never heard of the company punishing users of those tools even though they surely know they exist and are widely used.

**Comment by chylex** [comment]
Now that Discord has search, which it didn't at the inception of DHT, it should be easy for them to detect attempts at scraping the history.

*Technically* the end user data clause applies to Discord Developer TOS, which concerns data accessible through the Discord SDK, which DHT does not use. There is nothing I can see in the [User TOS](https://discordapp.com/terms) that would prohibit scraping data using the browser.

So far I'm not aware of anyone getting punished, on the other hand I was told that DHT logs were used to help Discord take down a nazi server, so I'm certain that they know about it.

**Comment by generic-github-user** [comment]
Thanks for the prompt response. I'm sure Discord does a _lot_ of activity monitoring for analytics (when you download your data package most if not all of that data is in it) but I'm not sure to what extent they use this to enforce the TOS - for example, I don't think you'll get automatically banned for using a browser-scraping tool.

While in theory they can tell that you're using one based on the way you scroll up through a page, I'm sure they have better things to worry about than archiving tools that don't access any data that isn't already available. I don't doubt that they are aware these tools exist, but it looks like they turn a blind eye to their use unless they already have a good reason to take down a user's account and need a cover-up.

I thought you meant that the server you mentioned was taken down on the grounds of TOS violation via DHT, but on closer inspection it seems like you were implying that they used information collected through DHT as evidence to take down a server. Personally I've never heard of someone being punished for a scraping-related violation, even on large servers where full backups are performed using scraping bots.

**Comment by chylex** [comment]
> I thought you meant that the server you mentioned was taken down on the grounds of TOS violation via DHT, but on closer inspection it seems like you were implying that they used information collected through DHT as evidence to take down a server.

Yes, apparently the server messages were wiped several times which completely removes them from Discord servers, but someone kept an archive using DHT and told me about the situation later. It's been a while though, so don't trust my memory too much.

**Comment by generic-github-user** [comment]
I see. I'm surprised that in that case Discord would accept those archives as proof since they are so easily modified but it's good they were able to use DHT to resolve the situation. For me it's mostly for peace of mind in temperamental chats or servers where a whole channel with thousands of messages can get nuked in a second. I'll close this issue if there are no objections.

**Comment by chylex** [comment]
I'm sure they'd check for similar or continued behavior on that and other servers, and since DHT stores all user and message IDs it's easy to cross-check those that haven't been deleted.

**Comment by generic-github-user** [comment]
Yeah, that sounds about right. I honestly wouldn't be surprised if Discord had some kind of cache/log to store evidence for future reference if something really bad is detected by their automated systems. Also, I didn't know DHT stores IDs, that's pretty neat. Thanks for the help.

**Comment by chylex** [comment]
Yea, DHT needs them to identify renamed entities (channels, users, messages), with the exception of servers/groups/DMs which are only tracked in terms of their channels.

**Comment by generic-github-user** [comment]
Thanks for the clarification and awesome job on this program. I'll close this now if you're okay with it.
