### ISSUE TITLE
DHT not working after Discord update

### ISSUE THREAD

**Issue by HydePod** [chylex/Discord-History-Tracker#77]
I can't save any messages anymore - get the error that "The selected channel is not visible in the channel list." I get this error both with the Discord desktop app and in the web browser w TamperMonkey.

I believe this is similar to other recent issues where the DHT didn't work after Discord pushed an update, that all ended up getting fixed (before this one). Is it possible to do an update so DHT works again? Thanks :)

**Comment by chylex** [comment]
That was fixed yesterday.

**Comment by eduarcor** [comment]
Happening again!!

**Comment by eduarcor** [comment]
And again!!
