### ISSUE TITLE
Images not showing right away in the Viewer

### ISSUE THREAD

**Issue by COLDsteem** [chylex/Discord-History-Tracker#79]
While viewing archived messages and either flipping pages or using the input box to jump to a certain page in history, images that were uploaded in the chat are not showing up right away. It takes some time for the images to load and show up in the Viewer... But until they show up, it looks like there are empty chat fields for a while, until images load. It would be useful if there was some kind of placeholder for each image, until they load and show up.

**Comment by chylex** [comment]
Firefox shows text while the image is loading (the text is wrong, but it's not just empty), while Chrome shows nothing. Maybe a placeholder image could work, but the image size isn't known until loaded so idk.

**Comment by COLDsteem** [comment]
Yeah, I've noticed it in Chrome only, didn't try Firefox or others. Placeholder could be just an average-sized box, not to foreshadow the real image size, but to indicate there is content and that it's loading. Could be a box with that loading animation circle GIF or similar... or at least an icon-sized little box with an X from the good ol' Microsoft IE days. :)

**Comment by chylex** [comment]
Gonna close it as unresolved, feel it's best for browsers to figure it out. Adding a placeholder when the image size isn't known would cause even more chaotic re-layouting, and overall it doesn't seem to be worth the effort when the images will get cached anyway, so it's only an issue for a few seconds on the first viewing.

**Comment by COLDsteem** [comment]
Sorry for reopening, but I've just noticed the way Discord does it. It shows the correct size of the image right away, but a blank rectangle (some darker shade of gray, different than background) with a loading indication (those two squares dancing around)... until it loads the correct image.

So it knows the exact image size in advance, then it loads it.

Examples:
![image](https://user-images.githubusercontent.com/46318908/87235810-b5e51000-c3e0-11ea-9e90-034eb72f6c4d.png)
![image](https://user-images.githubusercontent.com/46318908/87235811-be3d4b00-c3e0-11ea-9593-ff94d115fe96.png)

**Comment by chylex** [comment]
The new archive format in the app version of DHT includes some information about image dimensions, so I updated the viewer to set the expected dimensions wherever they are known, and made some improvements to the text that appears while the image is loading.

Currently there is no dimension information for image attachments (only for image embeds, and video thumbnails). I might start storing dimensions of image attachments, which would only apply to attachments in newly tracked (or re-tracked) messages.

**Comment by chylex** [comment]
The next update will track dimensions of image attachments (and also video attachments but those are currently shown as plain downloads without a preview).
