### ISSUE TITLE
Suggestion: "Last n days" feature / Split archive

### ISSUE THREAD

**Issue by UnforeseenOcean** [chylex/Discord-History-Tracker#80]
Archiving a big server often causes the browser or the client to crash -- an option to truncate messages older than X days (with a button that says "Save Last X Days") could come in handy.
![Image 098](https://user-images.githubusercontent.com/11834016/64922081-fa763e00-d805-11e9-97c5-3a6391ef48d8.png)

**Comment by chylex** [comment]
The website specifically states that DHT isn't intended for large servers with millions of messages. Better to use a different tool.

**Comment by UnforeseenOcean** [comment]
I'll need a way to make a truncated version of the archive myself then but the messages are not in chronological order for some reason...

**Comment by chylex** [comment]
Messages are stored as a mapping to allow fast search by their ID, so there is no defined order. Each message has a unix epoch timestamp if you want to sort them or compare dates. [tracker/savefile.js](https://github.com/chylex/Discord-History-Tracker/blob/master/src/tracker/savefile.js)
