### ISSUE TITLE
Viewer: Add light theme option

### ISSUE THREAD

**Issue by ssokolow** [chylex/Discord-History-Tracker#81]
Aside from terminal windows, which I don't use for chatting, I just can't get comfortable with light-on-dark themes. 

It'd probably be a good idea to mirror Discord's support for having a light theme in `viewer.html`.

(Normally, I'd claim that I want it for my own use but, in the near-term, I'll continue using a simple little `bottle.py`-based viewer of my own design which I hacked together back when your viewer appeared to be .NET-based. Mine has support for persistently hiding messages irrelevant to the reason I logged the conversation so I don't have to scroll past tangents we went on every time I read the chat log.)

**Comment by chylex** [comment]
One problem I see is that each browser behaves differently regarding saving settings (such as selected theme) in `file://` protocol, which is the intended way of using the viewer, so it'd probably be better to have it as a separate build of the viewer.

If someone's interested in making a PR, I can at least separate out the CSS that concerns theming into a single file, and add support for building multiple versions of the viewer.

**Comment by chylex** [comment]
Also the viewer has never been .NET based, you may be confusing it with Discord Chat Exporter.

**Comment by ssokolow** [comment]
> One problem I see is that each browser behaves differently regarding saving settings (such as selected theme) in file:// protocol, which is the intended way of using the viewer, so it'd probably be better to have it as a separate build of the viewer.

How is light/dark theme toggling different from the "Image Previews", "Message Formatting", and "Animated Emoji" toggles already under settings?

> Also the viewer has never been .NET based, you may be confusing it with Discord Chat Exporter.

Possibly. Something about how it was presented gave me that impression so, as inaccurate as thaty was, it's what motivated me to hack together my own viewer.

**Comment by chylex** [comment]
I didn't consider any of them to be permanent options and didn't look into persisting them, but a theme setting definitely seems like something a person would want to keep permanently.

Looking into it again, `localStorage` should nowadays work at least in Firefox and Chrome, so I can look into making all settings permanent and then add support for a theme setting.

**Comment by chylex** [comment]
If someone still wants to make a PR to add a light theme I can provide some guidance, but I'm not planning to do it myself so I'm closing the issue.
