### ISSUE TITLE
Re-add bookmarklet as an option for Firefox

### ISSUE THREAD

**Issue by ssokolow** [chylex/Discord-History-Tracker#82]
Given that DHT doesn't work with either of the open-source Firefox userscript hosts, and that [bug 1478037](https://bugzilla.mozilla.org/show_bug.cgi?id=1478037) has been closed, I decided to try creating a bookmarklet from the URL intended for the browser console... it works in my Firefox 69.0 install.

In fact, once I set `dht` as the bookmark keyword, it meant that I could just type <kbd>Ctrl+L</kbd>dht<kbd>Enter</kbd> to load DHT from the keyboard, which is a nice option.

**Comment by chylex** [comment]
Unfortunately Firefox 63+ removed the ability to do one-click bookmarklets [bug 1452645](https://bugzilla.mozilla.org/show_bug.cgi?id=1452645), but the new way doesn't seem too bad.

**Comment by ssokolow** [comment]
I think you got your link wrong. That's the bug for removing the "open bookmark in sidebar" feature and I don't see how that has anything to do with how a bookmarklet like DHT functions.

**Comment by chylex** [comment]
The old instructions used `<a rel="sidebar">` to add a bookmark on left click, since 63 it behaves like a normal link and left click opens it instead.

I wrote new instructions, they're a bit longer than they used to be with `rel="sidebar"` support.

**Comment by ssokolow** [comment]
Ahh. I'd completely forgotten about that.

I think that was originally Netscape's answer to Microsoft's Windows 9x Active Desktop Channels feature.
