### ISSUE TITLE
Broken with latest Discord update on 2019/11/07

### ISSUE THREAD

**Issue by prismane-0001** [chylex/Discord-History-Tracker#85]
Latest Discord update is causing issues. Clicking on the 'Start Tracking' button throws the following exception in Google Chrome (Windows 10):

```
db6c3ddb51620cee5d94.js:51` Uncaught TypeError: Cannot read property 'children' of undefined
    at Object.p (<anonymous>:1:1708)
    at <anonymous>:1:14925
    at n (<anonymous>:1:13439)
    at ie (<anonymous>:1:13643)
    at HTMLButtonElement.<anonymous> (<anonymous>:1:7821)
    at HTMLButtonElement.a (db6c3ddb51620cee5d94.js:51)
```

**Comment by HydePod** [comment]
Probably the same issue, but DHT tracker also not working again in Discord desktop app. Tracker shows up but when i hit 'Start Tracking' nothing happens. Thanks for maintaining this tool :)

**Comment by Ellen625** [comment]
I have the same issue
