### ISSUE TITLE
JSON format change

### ISSUE THREAD

**Issue by Imanton1** [chylex/Discord-History-Tracker#86]
(I have had to retype this, forgive my conciseness)
The 'm' key in the previous version (as of a few hours ago), when a zero length message was found, had a zero-length string, but now is absent in that case.
Is this intentional? If so, I will update my parser.

**Comment by chylex** [comment]
There have been several changes and deprecations recently, see https://github.com/chylex/Discord-History-Tracker/blob/master/src/tracker/savefile.js#L1-L72
