### ISSUE TITLE
Metadata of voice/video calls?

### ISSUE THREAD

**Issue by kmxz** [chylex/Discord-History-Tracker#87]
In the current implementation, a call will result in an trivial entry like `{ u: 0, t: 1500000000000 }`. It would be helpful if I can know it's a call.

I forked the project to [add the call-end time for myself](https://github.com/kmxz/Discord-History-Tracker/commit/e6a79bec3523d61b70702f93821e18758c8a8911). Not sure if anyone want to merge the change.

**Comment by chylex** [comment]
There's quite a few of these status messages. I think for now I'll just exclude them from the tracker, since there's no actual message so all of the different status metadata would have to be saved on a case-by-case basis.

**Comment by chylex** [comment]
If you're updating your fork, either revert the commit above or add a case for `discordMessage.type === 3` which covers call status messages.

**Comment by ficarra1002** [comment]
This would be a great feature

**Comment by chylex** [comment]
Closing in favor of #247.
