### ISSUE TITLE
Viewer: Not all messages display

### ISSUE THREAD

**Issue by Zexion711** [chylex/Discord-History-Tracker#88]
After trying to view a saved log in the viewer there will be pages of messages that don't display. It doesn't matter how many messages I save or how many are displayed per page, there will just be pages that will not load. If I open it as a text file I can search for the missing messages and they do show up like that but just not in the viewer.

**Comment by chylex** [comment]
I need a concrete archive file where it happens before I can investigate anything.

**Comment by Zexion711** [comment]
No problem, I am new to this type of stuff though so I do not know where that is. How do I get it for you?

**Comment by chylex** [comment]
It's possible the issue isn't with the archive but with the browser or viewer, make sure the tracker & viewer versions match (it's mentioned in dialogs tracker - Settings, viewer - About), and possibly try a different browser for the viewer.

**If that doesn't help then:**

Try saving a few messages from a public server (or private if all members consent) that you can upload publicly, and make sure it triggers the issue.

You can either upload the archive file here and it will be public, or email it to contact@chylex.com.

Mind that the archive file also exposes server/channel/user IDs, so if you're worried about privacy then you can also use Discord & DHT anonymously on public servers, or make a second account.

**Comment by Zexion711** [comment]
Yes! You are right it was just as simple as using an old version of the viewer. I didn't realise that was something that was updating and was using a build from back in April, silly me. Thank you for your help and thank you for creating this, it's a life saver!
