### ISSUE TITLE
Choose area for backup

### ISSUE THREAD

**Issue by Ar7ra** [chylex/Discord-History-Tracker#89]
Would it be at all possible to add the option to mark a certain area, as in "all messages between [Time Message One] and [Time Message Two]? It would be vastly helpful in saving important parts of conversations and projects.

**Comment by chylex** [comment]
You could scroll to message one, disable autoscroll, start and stop tracking to save message one (and a few around it).

Then go to message two, enable autoscroll, enable pausing after seeing a previously saved message, and start tracking. It will stop after it reaches message one.

**Comment by chylex** [comment]
Closing in favor of a new issue which covers overall improvements to the tracking settings, including an option to track until a specific date: #169
