### ISSUE TITLE
Unable to use tracker

### ISSUE THREAD

**Issue by VC38** [chylex/Discord-History-Tracker#9]
I was able to use the tracker two days ago, but now I am unable to. I tried different browsers, and the result was the same in all of them. Whenever I try to start tracking, the following error pops up in my console: d775a0c….js:98 Uncaught TypeError: Cannot read property 'id' of null
    at e.s (<anonymous>:1:11257)
    at s.i (<anonymous>:1:139)
    at XMLHttpRequest.onreadystatechange (<anonymous>:1:7250)
    at XMLHttpRequest.r (d775a0c….js:98)
The 'd775a' corresponds to: https://discordapp.com/assets/d775a0cd1a5cf763548a.js

This error pops up as soon as I attempt to start tracking and it stops the entire thing from working, so no messages are tracked for download. However, it will work on private DMs, all of which have been between me and one other user. Any help or fixes would be greatly appreciated, I rely on this tracker very heavily to keep archives of my group chats, which is where I'm seeing this issue. Thanks!

**Comment by chylex** [comment]
Discord updated its layout recently, will fix the issue as soon as possible.

**Comment by chylex** [comment]
Should be working now, the updated bookmark is at https://dht.chylex.com/
