### ISSUE TITLE
Tracker not saving logs

### ISSUE THREAD

**Issue by HydePod** [chylex/Discord-History-Tracker#90]
Tracker bar in Discord desktop app now just says '0 Messages from 1 Channel" and cant save any messages at all. Similar results with browser based method. Probably a repeat of previous issues where new Discord update makes the tracker temporarily unusable. Thanks for much for maintaining this tool. I love the program

**Comment by chylex** [comment]
I only now got the update, so I'll look into it soon.

**Comment by kamadan** [comment]
Hi, could you also update the version used on your site: https://dht.chylex.com/ . As of now, it is still using Beta v.17.

**Comment by chylex** [comment]
Updated.
