### ISSUE TITLE
Tracker not saving logs still... for me at least

### ISSUE THREAD

**Issue by CompGal** [chylex/Discord-History-Tracker#91]
For me, the Tracker bar in Discord (via the browser) is still saying '0 Messages from 1 Channel" and it won't save any messages at all. I do really love this tool and appreciate you keeping it updated. Hope you can fix it. Thank you so much!

**Comment by chylex** [comment]
If you click the Discord settings button and scroll all the way down in the menu column, there should be a bunch of version numbers on the bottom. What do they say?

**Comment by CompGal** [comment]
Stable 54329 (71b12da)
Windows 10 64-Bit

I copy-pasted the numbers on the bottom. Thank you for helping!

**Comment by chylex** [comment]
Does the DHT version tag in Settings say `BETA v.18, released 6 Feb 2020`?

**Comment by CompGal** [comment]
No... it says BETA v.17, released 11 Nov 2019

How do I update it please?
