### ISSUE TITLE
Indication while uploading big archive file

### ISSUE THREAD

**Issue by COLDsteem** [chylex/Discord-History-Tracker#92]
When uploading a big archive file, DHT just seems idle, until it shows the number of messages and channels loaded in archive file on the DHT bar.
It would be useful to add some kind of indicator or a loading sign, say those alternating three dots ... or whatever. So, before it shows number of messages and channels loaded on the bar, it could show that it's loading them, working, not being idle.
Very minor issue, but IMHO, worth mentioning.

**Comment by chylex** [comment]
I opened #141 which would solve issues with large archives, so I'm closing this one.
