### ISSUE TITLE
blank history is saved if the contact blocks you

### ISSUE THREAD

**Issue by ringtailedfox** [chylex/Discord-History-Tracker#97]
i've noticed that an empty history is saved if the person you're trying to save a chat history with blocked you.

**Comment by chylex** [comment]
Few clarifying questions:

- What do you mean by empty history? Does it remove existing history?
- Are you saving DMs, group chat, or server chat?
- Any errors in the browser console?

**Comment by ringtailedfox** [comment]
I mean that if i save the logs (as dht.txt) and import them into the viewer, they show up... but if I save the page including the logs as an HTML file, that file shows no logs within it... just as if I saved the page without loading/importing any logs at all.

**Comment by chylex** [comment]
If you save the viewer page in a browser, you're only saving the viewer itself, the logs don't magically stay loaded. There's an experimental feature for embedding logs https://github.com/chylex/Discord-History-Tracker/issues/20#issuecomment-528690867

**Comment by ringtailedfox** [comment]
I can save logs from other contacts that have not blocked me perfectly fine... it's when someone blocks me and I want to save the logs as evidence that this problem arises...

**Comment by chylex** [comment]
You just said you're saving the viewer page as an HTML file, that's not going to work regardless of whether someone blocked you.

**Comment by ringtailedfox** [comment]
then how are you supposed to save logs?

**Comment by chylex** [comment]
The file you get from the tracker is the logs. If you want to send them to someone else, either send both the log file & viewer, or follow the link I sent for a guide on how to embed the log file directly in the viewer (which I assume is what you're trying to do, but the feature is experimental).

**Comment by chylex** [comment]
Closing the issue, if you have any additional questions feel free to reopen.
